/**
 * Pipeline drafts for WI — AUTO-GENERATED by scripts/benefits-pipeline.js.
 * Do not edit manually. Regenerated from data/pipeline/WI/drafts.json
 * after each pipeline run for this state, or via --regen-index.
 *
 * Last updated: 2026-04-19T10:13:23.928Z
 */
import type { PipelineStateDrafts } from "../../pipeline-drafts-types";

export const drafts: PipelineStateDrafts = {
  "draftedAt": "2026-04-13",
  "programs": [
    {
      "id": "seniorcare-prescription-assistance",
      "name": "SeniorCare",
      "shortName": "SeniorCare",
      "tagline": "Help your parent save hundreds on prescriptions with $5 generics and $15 brand-name drugs.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Administered statewide by Wisconsin DHS; use any participating pharmacy (most WI pharmacies accept SeniorCare card)",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent is 65+ and paying high prescription costs, Wisconsin SeniorCare can reduce their drug bills to $5 for generics and $15 for brand-name medications. The program covers most FDA-approved drugs and coordinates with Medicare Part D to fill coverage gaps.\n\nSeniorCare works on income tiers — parents earning up to $25,536/year (single) or $34,624/year (couple) pay no deductible and get immediate $5/$15 copays. Higher income levels have deductibles from $500-$850 but still get the same low copays once met. The program has no asset limits and costs just $30/year to enroll.\n\nMost Wisconsin pharmacies accept the SeniorCare card, and coverage includes vaccines at no cost. Because SeniorCare coordinates as secondary insurance with Medicare, your parent can often save significantly compared to Medicare Part D alone.",
      "savingsRange": "$600 – $3,600/year",
      "savingsSource": "Estimated based on typical senior prescription usage with SeniorCare copay structure versus retail prices",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 65+",
          "Wisconsin resident",
          "Income varies by tier",
          "No asset limits",
          "$30 annual fee"
        ],
        "ageRequirement": "65+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Wisconsin resident",
          "U.S. citizen or qualifying immigrant",
          "Not enrolled in full-benefit Medicaid/BadgerCare Plus (some exceptions apply)",
          "Annual renewal required"
        ],
        "povertyLevelReference": "160%-240% FPL for different tiers"
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Call 800-657-2038 to request an application or download from the state website — processing takes 4-6 weeks.",
        "steps": [
          {
            "step": 1,
            "title": "Get the application",
            "description": "Call SeniorCare Customer Service at 800-657-2038 to request an application by mail, or download and print the form at https://www.dhs.wisconsin.gov/seniorcare"
          },
          {
            "step": 2,
            "title": "Gather required documents",
            "description": "Collect Social Security numbers, proof of income (tax returns or pay stubs), proof of Wisconsin residency, and information about other insurance coverage"
          },
          {
            "step": 3,
            "title": "Submit application with $30 fee",
            "description": "Mail the completed application with required documents and $30 enrollment fee to the address printed on the form"
          },
          {
            "step": 4,
            "title": "Wait for approval",
            "description": "Processing takes 4-6 weeks. Coverage starts the month after approval, not immediately upon application"
          }
        ],
        "processingTime": "4-6 weeks",
        "waitlist": null,
        "tip": "You can apply starting the month of your parent's 65th birthday — don't wait until they're already paying high prescription costs.",
        "urls": [
          {
            "label": "SeniorCare Application Form",
            "url": "https://www.dhs.wisconsin.gov/seniorcare"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security card for applicant",
        "Proof of age (birth certificate or driver's license)",
        "Proof of Wisconsin residency (utility bill, lease agreement, or tax return)",
        "Most recent tax return or Social Security award letter",
        "Pay stubs if still working (last 3 months)",
        "Pension or retirement income statements",
        "Medicare card (Parts A, B, and D if enrolled)",
        "Other insurance cards if applicable",
        "$30 enrollment fee (check or money order)",
        "Bank account information for spouse if married"
      ],
      "contacts": [
        {
          "label": "SeniorCare Customer Service",
          "phone": "800-657-2038",
          "description": "Applications, enrollment questions, and general program information",
          "hours": "Mon-Fri 8am-5pm CT"
        },
        {
          "label": "Wisconsin 2-1-1",
          "phone": "2-1-1",
          "description": "Free helpline for all Wisconsin social services and benefits",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "For married couples, both spouses' income counts even if only one person applies for SeniorCare",
        "Level 3 participants must meet a monthly spenddown equal to their income over 240% FPL before benefits kick in",
        "Annual renewal is required every year with another $30 fee — missing renewal means losing coverage",
        "SeniorCare works as secondary insurance, so keep your Medicare Part D or other prescription coverage active"
      ],
      "relatedPrograms": [
        "Medicare Part D",
        "Wisconsin BadgerCare Plus",
        "Medicare Savings Programs",
        "FoodShare (SNAP)"
      ],
      "contentSections": [
        {
          "type": "tier-comparison",
          "title": "Income Tiers and Costs",
          "content": {
            "tiers": [
              {
                "name": "Level 1",
                "income": "≤160% FPL (≤$25,536 single, ≤$34,624 couple)",
                "deductible": "$0",
                "copays": "$5 generic, $15 brand-name",
                "vaccines": "$0"
              },
              {
                "name": "Level 2A",
                "income": "160%-200% FPL ($25,537-$31,920 single)",
                "deductible": "$500 per person",
                "copays": "$5 generic, $15 brand-name (after deductible)",
                "vaccines": "$0"
              },
              {
                "name": "Level 2B",
                "income": "200%-240% FPL ($31,921-$38,304 single)",
                "deductible": "$850 per person",
                "copays": "$5 generic, $15 brand-name (after deductible)",
                "vaccines": "$0"
              },
              {
                "name": "Level 3",
                "income": ">240% FPL (no upper limit)",
                "deductible": "$850 per person (after monthly spenddown)",
                "copays": "$5 generic, $15 brand-name (after deductible)",
                "vaccines": "$0"
              }
            ]
          }
        }
      ],
      "faqs": [
        {
          "question": "Can my parent keep SeniorCare if they're already on Medicare Part D?",
          "answer": "Yes, and they should keep both. SeniorCare coordinates with Medicare Part D as secondary coverage, often providing better copays than Part D alone. Your parent will use their SeniorCare card at the pharmacy, and the programs will coordinate automatically."
        },
        {
          "question": "What happens if my parent's income puts them in Level 3 with the monthly spenddown?",
          "answer": "Each month, your parent must spend an amount equal to their income over 240% FPL on medical expenses before SeniorCare coverage begins. For example, if they're $200 over the limit, they pay the first $200 in prescription costs, then SeniorCare covers the rest with the $5/$15 copays."
        },
        {
          "question": "Why was my parent's application denied if they're on BadgerCare Plus?",
          "answer": "People enrolled in full-benefit Medicaid or BadgerCare Plus cannot enroll in SeniorCare. However, those with limited Medicaid like Qualified Medicare Beneficiary (QMB) or SLMB programs can still qualify. Call 800-657-2038 to clarify which type of Medicaid coverage your parent has."
        },
        {
          "question": "Does my spouse's income count if only my parent is applying?",
          "answer": "Yes, if your parent is married and living with their spouse, both incomes are combined to determine the SeniorCare tier, even if only one spouse applies. This is different from some other programs that look at individual income only."
        },
        {
          "question": "What happens if we forget to renew by the deadline?",
          "answer": "Coverage ends, and your parent will lose SeniorCare benefits until they reapply. There's no grace period, so mark the renewal date on your calendar and pay the $30 annual fee on time. The renewal notice comes by mail with instructions."
        },
        {
          "question": "Can I help my parent apply if they have dementia or can't manage paperwork?",
          "answer": "Yes, family members can help complete the application. If your parent cannot sign documents due to cognitive issues, you may need to establish power of attorney or guardianship first. Call SeniorCare Customer Service at 800-657-2038 to discuss your specific situation and what documentation they'll accept."
        },
        {
          "question": "Which pharmacies accept SeniorCare, and what if our pharmacy doesn't participate?",
          "answer": "Most Wisconsin pharmacies accept SeniorCare cards, including major chains and independent pharmacies. If your parent's current pharmacy doesn't participate, they can switch to any participating pharmacy. Call 800-657-2038 for a list of participating pharmacies in your area."
        },
        {
          "question": "Are there prescription drugs that SeniorCare won't cover?",
          "answer": "SeniorCare covers most FDA-approved prescription drugs and prefers generics when available. Some brand-name drugs may require prior authorization from your parent's doctor. Experimental drugs and over-the-counter medications are typically not covered. Check with the pharmacy or call customer service about specific medications."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "savings",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "step-journey",
        "hasLocationFinder": false,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "Pill",
      "phone": "800-657-2038",
      "sourceUrl": "https://www.dhs.wisconsin.gov/seniorcare/index.htm",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "elder-benefit-specialist",
      "name": "Elder Benefit Specialist (EBS) Program",
      "shortName": "Elder Benefit Specialist",
      "tagline": "Free expert help navigating Medicare, Social Security, food stamps, and housing assistance for your parent.",
      "programType": "resource",
      "complexity": "simple",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local Aging and Disability Resource Centers (ADRCs), county aging offices, tribal partners; find via FindMyADRC.org",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent is struggling with Social Security denials, Medicare confusion, or benefit applications, Wisconsin's Elder Benefit Specialists provide free one-on-one help. These trained advocates, supervised by elder law attorneys, can assist with appeals, compare insurance options, help with FoodShare applications, and protect against debt collection — all at no cost.\n\nBecause Elder Benefit Specialists work for you (not insurance companies or government agencies), they provide unbiased guidance on which programs make the most financial sense. Your parent qualifies regardless of income or assets — the only requirement is living in Wisconsin and being 60 or older.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "Live in Wisconsin",
          "No income limits",
          "No asset limits"
        ],
        "ageRequirement": "60+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Must live in Wisconsin"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call the statewide helpline at 1-844-947-2372 — services begin immediately upon contact.",
        "steps": [
          {
            "step": 1,
            "title": "Call the statewide helpline",
            "description": "Call 1-844-WIS-ADRC (1-844-947-2372) to be connected with your local Elder Benefit Specialist."
          },
          {
            "step": 2,
            "title": "Or find your local office",
            "description": "Visit FindMyADRC.org to locate your county's Aging and Disability Resource Center or contact your local county aging office directly."
          },
          {
            "step": 3,
            "title": "Begin services immediately",
            "description": "No formal application required — your Elder Benefit Specialist will start helping with your specific benefit questions right away."
          }
        ],
        "processingTime": "Services provided immediately upon contact",
        "waitlist": null,
        "tip": "Bring any benefit-related paperwork to your first meeting — denial letters, income statements, or insurance documents help specialists understand your situation faster.",
        "urls": [
          {
            "label": "Find Your Local ADRC",
            "url": "https://findmyadrc.org"
          }
        ]
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "Wisconsin ADRC Helpline",
          "phone": "1-844-947-2372",
          "description": "Statewide helpline connecting you to local Elder Benefit Specialists",
          "hours": "Business hours vary by county"
        },
        {
          "label": "Wisconsin Department of Health Services",
          "phone": "(608) 266-1865",
          "description": "General information about Elder Benefit Specialist program",
          "hours": "Mon-Fri 8am-4:30pm CT"
        }
      ],
      "applicationNotes": null,
      "relatedPrograms": [
        "Wisconsin SeniorCare",
        "FoodShare Wisconsin",
        "Wisconsin Home Energy Assistance Program",
        "Medicare Part D Extra Help"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can I call on behalf of my parent who has dementia?",
          "answer": "Yes, but your parent will need to sign a release of information form allowing the Elder Benefit Specialist to discuss their case with you. If your parent cannot sign due to cognitive impairment, bring documentation of your legal authority (power of attorney or guardianship papers)."
        },
        {
          "question": "What's the difference between an Elder Benefit Specialist and a Medicare insurance agent?",
          "answer": "Elder Benefit Specialists work for you, not insurance companies, and receive no commissions. They can compare all available options objectively and help with appeals or denials. Insurance agents can only sell their company's products and cannot provide advocacy services."
        },
        {
          "question": "Will this cost anything or are there hidden fees?",
          "answer": "Elder Benefit Specialist services are completely free. Some offices accept donations, but donations are never required. If your specialist identifies that you need full legal representation, they will refer you to appropriate legal aid services."
        },
        {
          "question": "Can they help if my parent already applied for benefits and was denied?",
          "answer": "Yes, helping with appeals and benefit denials is a core service. Elder Benefit Specialists can review denial letters, help gather additional documentation, and guide you through the appeals process for Social Security, Medicare, Medicaid, and other programs."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": null,
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "phone-cta",
        "hasLocationFinder": true,
        "hasDocumentChecklist": false,
        "visualTone": "minimal"
      },
      "icon": "Compass",
      "phone": "1-844-947-2372",
      "sourceUrl": "https://www.dhs.wisconsin.gov/benefit-specialists/ebs.htm",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "senior-employment-program-wise",
      "name": "Wisconsin Senior Employment Program (WISE)",
      "shortName": "WISE Employment",
      "tagline": "Paid part-time work and skills training for unemployed adults 55+ earning under $31,200/year for a family of two.",
      "programType": "employment",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Fox Valley Workforce Development Board (920-229-5557)",
            "type": "service-area"
          },
          {
            "name": "GWAAR (608-242-4928 or 608-243-5670, Dane County)",
            "type": "service-area"
          },
          {
            "name": "Employ Milwaukee",
            "type": "service-area"
          },
          {
            "name": "Job Center of Wisconsin (detwise@dwd.wisconsin.gov)",
            "type": "service-area"
          },
          {
            "name": "CWI Works subgrantee network including Wisconsin",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent is 55+ and unemployed with limited income, WISE provides paid part-time work (typically 20 hours per week) at minimum wage while building job skills for permanent employment. Your parent earns a paycheck while receiving job training, work experience, and individual counseling to transition to unsubsidized employment.\n\nThe program places participants in community service positions at local nonprofits and government agencies. Because WISE pays at least minimum wage for all hours worked, your parent receives steady income while developing marketable skills. Veterans and participants over 65 get priority enrollment — others may face waiting periods depending on local provider capacity.\n\nTo qualify, your family income must be at or below 125% of the federal poverty level (exact dollar amounts change annually). Your parent must be a Wisconsin resident and actively seeking work. The program is administered by different regional providers across the state, so contact your local office directly to apply.",
      "savingsRange": "",
      "savingsSource": "Paid employment program",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 55+",
          "Unemployed",
          "Family income ≤125% federal poverty level",
          "Wisconsin resident"
        ],
        "ageRequirement": "55+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Must be unemployed and actively seeking work",
          "Wisconsin resident",
          "Poor employment prospects due to age, disability, or other barriers"
        ],
        "povertyLevelReference": "125% FPL"
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call your regional workforce development provider — no standardized statewide application exists.",
        "steps": [
          {
            "step": 1,
            "title": "Find your regional provider",
            "description": "Call (920) 229-5557 for Fox Valley area, (608) 242-4928 for Dane County, or email detwise@dwd.wisconsin.gov to find your local Job Center of Wisconsin office."
          },
          {
            "step": 2,
            "title": "Complete intake assessment",
            "description": "Your local provider will assess your eligibility, work history, and training needs. Bring documentation of age, residency, unemployment status, and family income."
          },
          {
            "step": 3,
            "title": "Wait for placement",
            "description": "Veterans and people 65+ get priority. Others join a waitlist based on local capacity and funding availability."
          },
          {
            "step": 4,
            "title": "Start training position",
            "description": "Once placed, you'll work 20 hours per week at a community service host site while receiving job coaching and skills development."
          }
        ],
        "processingTime": "Not specified — varies by regional provider capacity",
        "waitlist": "Veterans and participants over 65 get priority enrollment — others may face waiting periods",
        "tip": "Call multiple regional providers if you live near county boundaries — availability varies significantly by area.",
        "urls": [
          {
            "label": "Wisconsin Job Center Directory",
            "url": "https://www.wisconsinjobcenter.org/ow/"
          }
        ]
      },
      "documentsNeeded": [
        "Valid government-issued photo ID",
        "Birth certificate or passport to verify age 55+",
        "Proof of Wisconsin residency (utility bill, lease, or driver's license)",
        "Social Security card",
        "Most recent tax return or tax transcript",
        "Unemployment insurance documents if receiving benefits",
        "Bank statements for all accounts (last 3 months)",
        "Documentation of all household income sources",
        "Proof of job search activities (applications, rejection letters)",
        "Military discharge papers (DD-214) if veteran or military spouse",
        "Medical documentation if claiming disability affects employment"
      ],
      "contacts": [
        {
          "label": "Fox Valley Workforce Development Board",
          "phone": "(920) 229-5557",
          "description": "Serves northeast Wisconsin region",
          "hours": "Business hours"
        },
        {
          "label": "GWAAR (Dane County)",
          "phone": "(608) 242-4928",
          "description": "Serves Dane County area",
          "hours": "Business hours"
        },
        {
          "label": "DWD Employment Programs",
          "phone": null,
          "description": "Email detwise@dwd.wisconsin.gov for statewide program information",
          "hours": "Business hours"
        },
        {
          "label": "Wisconsin 2-1-1",
          "phone": "2-1-1",
          "description": "Free 24/7 helpline to find local workforce services",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "Veterans and qualified military spouses get first priority for enrollment, followed by participants age 65 and older",
        "Each regional provider operates independently — program availability, wait times, and host agencies vary significantly by location",
        "Income limit applies to total family income, not just the applicant's individual income",
        "This is temporary training employment with the goal of transitioning to permanent unsubsidized work — not a permanent job program"
      ],
      "relatedPrograms": [
        "Wisconsin Works (W-2)",
        "FoodShare Wisconsin (SNAP)",
        "Wisconsin Home Energy Assistance Program (WHEAP)",
        "BadgerCare Plus (Medicaid)"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my parent work at WISE while receiving Social Security retirement benefits?",
          "answer": "Yes, but Social Security has earnings limits that could reduce benefits if your parent earns too much. In 2026, retirees under full retirement age can earn $22,320 annually before Social Security reduces benefits. Contact Social Security at (800) 772-1213 to understand how WISE wages might affect payments."
        },
        {
          "question": "What if my parent has been unemployed for years — does that hurt their chances?",
          "answer": "No, long-term unemployment actually supports eligibility since WISE specifically targets people with poor employment prospects due to age or other barriers. The program is designed for exactly this situation."
        },
        {
          "question": "How long can my parent stay in the WISE program?",
          "answer": "The program is temporary training designed to transition participants to unsubsidized employment. Specific time limits vary by regional provider and individual progress toward employment goals."
        },
        {
          "question": "Can I apply for WISE and unemployment benefits at the same time?",
          "answer": "No, you cannot receive unemployment insurance while employed in WISE since you'll be earning wages. You may need to choose between continuing unemployment benefits or accepting a WISE position."
        },
        {
          "question": "What happens if my parent gets sick and can't work their WISE hours?",
          "answer": "Contact your regional provider immediately. Policies for medical leave or temporary absences vary by provider. Some may hold your position while others may need to fill it due to limited slots."
        },
        {
          "question": "Does WISE provide health insurance or other benefits besides wages?",
          "answer": "WISE provides wages, skills training, job counseling, and yearly physical exams. Health insurance is not typically provided. Your parent should maintain existing coverage through BadgerCare Plus, Medicare, or other sources."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "Briefcase",
      "phone": "(920) 229-5557",
      "sourceUrl": "https://www.dhs.wisconsin.gov/publications/p00409-2024-2027.pdf",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "family-care",
      "name": "Family Care",
      "shortName": "Family Care",
      "tagline": "Home and community-based care services that help your parent avoid nursing home placement while staying in their own home or community.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "local",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local ADRCs statewide",
            "type": "service-area"
          },
          {
            "name": "Managed Care Organizations (CMOs) like Community Care Inc., Anthem, My Choice Wisconsin",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent needs daily help with activities like bathing, dressing, or meal preparation, Family Care provides comprehensive home and community services to help them avoid nursing home placement. Because the program covers personal care, respite care, home modifications, and care coordination under one managed care plan, your parent gets all their long-term care services coordinated by a single team instead of juggling multiple providers.\n\nYour parent must be 65+ (or 18-64 with a disability), meet Wisconsin Medicaid income and asset limits, and pass a functional assessment showing they need the level of care typically provided in a nursing facility. The program is only available in participating Wisconsin counties where managed care organizations provide services. There are no waitlists once you're approved, but enrollment requires both financial Medicaid eligibility and a clinical assessment of care needs.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 65+ or 18-64 with disability",
          "Wisconsin resident in participating county",
          "Meet Medicaid income and asset limits",
          "Need nursing facility level of care",
          "Require help with daily activities"
        ],
        "ageRequirement": "65+",
        "incomeTable": null,
        "assetLimits": {
          "individual": 2000,
          "couple": null,
          "countedAssets": [
            "Bank accounts",
            "Investments",
            "Life insurance cash value"
          ],
          "exemptAssets": [
            "Primary residence",
            "Personal vehicle"
          ],
          "homeEquityCap": null
        },
        "functionalRequirement": "Must need Nursing Facility Level of Care (a clinical assessment showing your parent needs daily assistance with activities like bathing, eating, mobility, meal preparation, or medication management)",
        "otherRequirements": [
          "Wisconsin resident in a participating county/region",
          "Financially eligible for Medicaid"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Contact your local Aging and Disability Resource Center (ADRC) to start the screening process — they handle both the functional assessment and Medicaid application assistance.",
        "steps": [
          {
            "step": 1,
            "title": "Contact your local ADRC",
            "description": "Find your local Aging and Disability Resource Center using the ADRC locator online or call them directly. They provide free screening and application assistance."
          },
          {
            "step": 2,
            "title": "Complete functional screening",
            "description": "Your ADRC will conduct the Long Term Care Functional Screen (LTC FS) to determine if your parent meets Nursing Facility Level of Care requirements."
          },
          {
            "step": 3,
            "title": "Apply for Medicaid",
            "description": "Complete the Medicaid application online or on paper. Your ADRC can help with this process and submitting forms to the income maintenance agency."
          },
          {
            "step": 4,
            "title": "Choose managed care organization",
            "description": "Once approved, work with your ADRC to select from available CMOs in your area (like Community Care, Anthem, or My Choice Wisconsin) and complete enrollment."
          }
        ],
        "processingTime": "Not specified",
        "waitlist": "No waitlists for program participation",
        "tip": "Start with your ADRC — they're your single point of contact for both the functional assessment and Medicaid application, which saves time coordinating between multiple agencies.",
        "urls": [
          {
            "label": "Wisconsin DHS Family Care Application Info",
            "url": "https://www.dhs.wisconsin.gov/familycare/apply.htm"
          }
        ]
      },
      "documentsNeeded": [
        "Valid government-issued photo ID",
        "Proof of Wisconsin residency (utility bill, lease, or state-issued document)",
        "Social Security cards for all household members",
        "Medicare card (if applicable)",
        "Most recent Social Security award letter",
        "Pension or retirement income statements",
        "Bank statements for all accounts (last 3 months)",
        "Investment documents (stocks, bonds, annuities)",
        "Property documents (deeds, tax statements)",
        "Life insurance policies with cash values",
        "Vehicle titles and registration",
        "Medical records documenting need for daily assistance",
        "Current medication list",
        "Documentation of current care services or providers"
      ],
      "contacts": [
        {
          "label": "ADRC Locator",
          "phone": null,
          "description": "Find your local Aging and Disability Resource Center for screening and application assistance",
          "hours": "Varies by location"
        },
        {
          "label": "Wisconsin 2-1-1",
          "phone": "2-1-1",
          "description": "General information and referral to local ADRCs and other services",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "Family Care is not available statewide — you must live in a participating county where managed care organizations offer the program",
        "Both financial Medicaid eligibility AND functional screening are required — meeting income limits alone is not sufficient for enrollment",
        "If your parent is already on Medicaid but hasn't had a functional assessment, they still need the Long Term Care Functional Screen",
        "Medicare beneficiaries can still qualify for Family Care if they meet Medicaid financial rules and functional requirements"
      ],
      "relatedPrograms": [
        "Wisconsin Medicaid",
        "IRIS (Include, Respect, I Self-Direct)",
        "Program of All-Inclusive Care for the Elderly (PACE)"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my parent keep their house if they qualify for Family Care?",
          "answer": "Yes, your parent's primary residence is exempt from Medicaid asset limits regardless of value. Family Care is specifically designed to help people stay in their homes and communities rather than enter nursing facilities."
        },
        {
          "question": "What if we live in a county that doesn't offer Family Care?",
          "answer": "Family Care is only available in participating counties with managed care organizations. Contact your local ADRC to learn what other long-term care options are available in your area, such as traditional Medicaid waiver programs."
        },
        {
          "question": "Can I apply for Family Care on behalf of my elderly parent?",
          "answer": "Yes, family members can help with the application process. If your parent cannot make decisions for themselves, you may need legal documentation like power of attorney or guardianship to act on their behalf."
        },
        {
          "question": "How do I choose between the different managed care organizations?",
          "answer": "Your ADRC will explain which CMOs serve your area and their differences in providers, services, and care coordination approaches. You can switch CMOs during certain enrollment periods if you're not satisfied with your choice."
        },
        {
          "question": "What happens if my parent's care needs increase after enrollment?",
          "answer": "Your parent's care plan is regularly reassessed and can be adjusted as their needs change. The CMO care team will modify services and supports without requiring a new application as long as they continue to meet program eligibility."
        },
        {
          "question": "Can my parent have both Medicare and Family Care?",
          "answer": "Yes, many Family Care participants have Medicare for their medical needs and Family Care for long-term care services. The programs work together to provide comprehensive coverage without duplication."
        },
        {
          "question": "How long does it take to start receiving services after approval?",
          "answer": "While there are no program waitlists, the timeline for starting services depends on completing assessments, developing your care plan, and arranging providers. Your CMO care coordinator will work to start essential services as quickly as possible."
        },
        {
          "question": "What if my parent needs care immediately while we're waiting for approval?",
          "answer": "Contact your ADRC about emergency or crisis services that may be available immediately. Some urgent needs can be addressed while the application is being processed, especially if your parent is being discharged from a hospital."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "asset-focused",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "House",
      "phone": "2-1-1",
      "sourceUrl": "https://www.dhs.wisconsin.gov/familycare/apply.htm",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "iris-self-directed-care",
      "name": "IRIS (Include, Respect, I Self-Direct)",
      "shortName": "IRIS",
      "tagline": "Your parent controls their care budget to hire providers and buy services they choose.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local ADRCs (find via dhs.wisconsin.gov/adrc/consumer/index.htm)",
            "type": "service-area"
          },
          {
            "name": "Tribal ADRS (dhs.wisconsin.gov/adrc/consumer/tribes.htm)",
            "type": "service-area"
          }
        ]
      },
      "intro": "IRIS gives your parent control over their long-term care budget instead of being assigned specific providers. Your parent gets a monthly budget based on their assessed needs, then chooses and hires their own caregivers, purchases approved services, and manages their care team. Because your parent controls the budget directly, they can hire family members as paid caregivers or find providers that match their preferences and schedule.\n\nTo qualify, your parent must need nursing home level care but want to stay in their own home or community setting. They must meet Wisconsin Medicaid income and asset rules, including a home equity limit of $750,000 if they live in their home. The program covers personal care, adult day services, home modifications, and other approved supports — your parent decides how to spend their allocated budget.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 18+",
          "Wisconsin Medicaid eligible",
          "Nursing home level of care needed",
          "Must live in community setting"
        ],
        "ageRequirement": "18+",
        "incomeTable": null,
        "assetLimits": {
          "individual": null,
          "couple": null,
          "countedAssets": [],
          "exemptAssets": [
            "Home if applicant lives there or intends to return (equity ≤$750,000)",
            "Home if spouse lives there",
            "Home if minor child (<18) lives there",
            "Home if disabled child lives there"
          ],
          "homeEquityCap": 750000
        },
        "functionalRequirement": "Must need nursing home level care or intermediate care facility level care, determined through Wisconsin Adult Long-Term Care Functional Screen assessing daily living activities",
        "otherRequirements": [
          "Wisconsin resident",
          "U.S. citizen or qualifying immigrant",
          "Cannot live in skilled nursing facility or community-based residential facility",
          "Must cooperate with medical support requirements"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Start by calling your local Aging and Disability Resource Center to complete a functional assessment and apply for Medicaid.",
        "processingTime": "Not specified",
        "waitlist": null,
        "tip": "Having Medicaid already approved speeds up the IRIS enrollment process significantly.",
        "steps": [
          {
            "step": 1,
            "title": "Contact your local ADRC",
            "description": "Find your county's Aging and Disability Resource Center at dhs.wisconsin.gov/adrc/consumer/index.htm or tribal office at dhs.wisconsin.gov/adrc/consumer/tribes.htm. They will schedule your Long-Term Care Functional Screen."
          },
          {
            "step": 2,
            "title": "Complete functional assessment",
            "description": "Complete the Wisconsin Adult Long-Term Care Functional Screen with your ADRC to determine if your parent needs nursing home level care."
          },
          {
            "step": 3,
            "title": "Apply for Wisconsin Medicaid",
            "description": "Apply online or submit paper application to your local income maintenance agency. Your ADRC can help with this process."
          },
          {
            "step": 4,
            "title": "Select Fiscal Employer Agent",
            "description": "Choose a Fiscal Employer Agent (FEA) with help from your ADRC. The FEA will handle payroll and tax responsibilities when your parent hires caregivers."
          }
        ],
        "urls": [
          {
            "label": "Find your local ADRC",
            "url": "https://www.dhs.wisconsin.gov/adrc/consumer/index.htm"
          },
          {
            "label": "Tribal ADRS offices",
            "url": "https://www.dhs.wisconsin.gov/adrc/consumer/tribes.htm"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security cards for all household members",
        "Proof of Wisconsin residency (utility bill, lease, or state-issued document)",
        "Proof of citizenship or immigration status",
        "Most recent Social Security award letter or disability determination",
        "Bank statements for all accounts (last 3 months)",
        "Property documents including home deed and tax statements",
        "Investment documents (stocks, bonds, annuities, trust agreements)",
        "Life insurance policies with cash values",
        "Vehicle titles and registration",
        "Medical records documenting need for daily assistance",
        "Current prescription list and medication management needs",
        "Documentation of current care providers or services",
        "Power of attorney documents if someone will apply on behalf of parent"
      ],
      "contacts": [
        {
          "label": "ADRC Helpline",
          "phone": "1-855-677-2372",
          "description": "Wisconsin Aging and Disability Resource Center helpline",
          "hours": "Mon-Fri 8am-4:30pm CT"
        },
        {
          "label": "Wisconsin 2-1-1",
          "phone": "2-1-1",
          "description": "Free 24/7 helpline for all social services and program information",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "You must live in an eligible community setting — not in a nursing facility or certain residential care facilities",
        "Self-direction means your parent manages their budget, hires and fires providers, and follows program rules — the FEA handles payroll but not service decisions",
        "All hired providers must enroll with Wisconsin's ForwardHealth Portal before they can be paid",
        "Having existing Medicaid coverage speeds up IRIS enrollment since financial eligibility is already established"
      ],
      "relatedPrograms": [
        "Family Care",
        "Program of All-Inclusive Care for the Elderly (PACE)",
        "Wisconsin Medicaid",
        "FoodShare Wisconsin"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my parent hire family members as paid caregivers through IRIS?",
          "answer": "Yes, your parent can hire family members as caregivers using their IRIS budget. The family member must enroll with ForwardHealth Portal as a provider and follow all program requirements. The Fiscal Employer Agent will handle payroll, taxes, and workers' compensation."
        },
        {
          "question": "What happens if my parent's care needs change after they're enrolled?",
          "answer": "IRIS budgets can be adjusted when care needs change. Contact your parent's IRIS Consultant Agency to request a reassessment. If the functional screen shows increased needs, the budget may be increased. Regular reassessments ensure the budget matches current needs."
        },
        {
          "question": "How much control does my parent really have over their care budget?",
          "answer": "Your parent has significant control but must follow program rules. They choose and hire all providers, decide when services are provided, and can change providers anytime. However, all purchases must be from the approved services list and all providers must be enrolled with ForwardHealth."
        },
        {
          "question": "What if my parent owns their home but it's worth more than $750,000?",
          "answer": "If your parent lives in their home or intends to return to it, they can keep it as long as the equity doesn't exceed $750,000. If equity exceeds this limit, they won't qualify for Medicaid and therefore not for IRIS."
        },
        {
          "question": "Can my parent use IRIS while also getting other Medicaid services?",
          "answer": "IRIS coordinates with other Medicaid services, but your parent cannot be enrolled in Family Care or other long-term care programs at the same time. Regular Medicaid services like doctor visits and prescriptions continue alongside IRIS."
        },
        {
          "question": "What's the difference between IRIS and Family Care in Wisconsin?",
          "answer": "IRIS gives your parent control over their budget to hire their own providers, while Family Care assigns a care management organization that coordinates services for them. IRIS offers more control but requires more responsibility for managing the budget and providers."
        },
        {
          "question": "How long does it take to get approved for IRIS after applying?",
          "answer": "Processing time varies by county and depends on whether your parent already has Medicaid approved. The functional assessment and Medicaid application are the main time factors. Contact your local ADRC for current processing times in your area."
        },
        {
          "question": "What happens to the IRIS budget if my parent goes to the hospital?",
          "answer": "The IRIS budget may be suspended or reduced during hospital stays since care needs are being met by the hospital. When your parent returns home, the budget typically resumes. Notify the IRIS Consultant Agency about hospital admissions to avoid payment issues."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "asset-focused",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "HandCoins",
      "phone": "1-855-677-2372",
      "sourceUrl": "https://www.dhs.wisconsin.gov/iris/index.htm",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    }
  ],
  "stateOverview": {
    "intro": "Wisconsin offers 5 key programs to help your aging parent — 3 financial benefits, 1 employment program, and 1 free resource. Your parent could save hundreds monthly on prescriptions through SeniorCare, get paid part-time work through WISE if they're under income limits, or receive home care services through Family Care to avoid nursing home placement. The Elder Benefit Specialist Program provides free expert help navigating all these options plus Medicare and Social Security. Start by calling an Elder Benefit Specialist at your local Aging and Disability Resource Center — they'll help you identify which programs your parent qualifies for and handle applications.",
    "startHere": [
      {
        "name": "Elder Benefit Specialist (EBS) Program",
        "programId": "elder-benefit-specialist-ebs-program",
        "why": "Free expert help to identify which programs your parent qualifies for and navigate applications."
      },
      {
        "name": "SeniorCare",
        "programId": "seniorcare",
        "why": "Immediate prescription savings with $5 generics and $15 brand-name drugs."
      },
      {
        "name": "Family Care",
        "programId": "family-care",
        "why": "Comprehensive home care services to help your parent avoid nursing home placement."
      }
    ],
    "byNeed": [
      {
        "need": "Help paying for prescriptions",
        "programs": [
          "SeniorCare"
        ],
        "description": "Reduced-cost medications for Wisconsin seniors."
      },
      {
        "need": "Home care to avoid nursing homes",
        "programs": [
          "Family Care",
          "IRIS"
        ],
        "description": "Services to help your parent stay in their home or community."
      },
      {
        "need": "Part-time work and income",
        "programs": [
          "Wisconsin Senior Employment Program (WISE)"
        ],
        "description": "Paid employment and skills training for adults 55+ under income limits."
      },
      {
        "need": "Free advice and advocacy",
        "programs": [
          "Elder Benefit Specialist (EBS) Program"
        ],
        "description": "Expert help navigating Medicare, Social Security, and benefit programs."
      }
    ],
    "quickFacts": [
      "Elder Benefit Specialists are available at every Wisconsin Aging and Disability Resource Center for free consultations",
      "SeniorCare is Wisconsin's state prescription drug program with lower costs than most Medicare Part D plans",
      "Family Care and IRIS both require Nursing Facility Level of Care assessment but let your parent stay at home"
    ],
    "resourcesVsBenefits": "The Elder Benefit Specialist Program is free to all Wisconsin seniors regardless of income — call your local Aging and Disability Resource Center anytime for help. The other four programs require qualification: SeniorCare has income limits, Family Care and IRIS require clinical assessments showing your parent needs daily care assistance, and WISE requires unemployment and income under $31,200/year for a family of two."
  }
};
