/**
 * Utility functions for the provider details page.
 */

import type { ProfileCategory } from "@/lib/types";
import type { Provider } from "@/components/providers/ProviderCard";
import { createClient } from "@/lib/supabase/server";
import {
  type Provider as IOSProvider,
  PROVIDERS_TABLE,
  toCardFormat,
} from "@/lib/types/provider";

// ============================================================
// Initials
// ============================================================

export function getInitials(name: string): string {
  return name
    .split(/\s+/)
    .map((word) => word[0])
    .filter(Boolean)
    .slice(0, 2)
    .join("")
    .toUpperCase();
}

// ============================================================
// Category formatting
// ============================================================

const categoryLabels: Record<ProfileCategory, string> = {
  home_care_agency: "Home Care",
  home_health_agency: "Home Health",
  hospice_agency: "Hospice",
  independent_living: "Independent Living",
  assisted_living: "Assisted Living",
  memory_care: "Memory Care",
  nursing_home: "Nursing Home",
  inpatient_hospice: "Inpatient Hospice",
  rehab_facility: "Rehabilitation",
  adult_day_care: "Adult Day Care",
  wellness_center: "Wellness Center",
  private_caregiver: "Private Caregiver",
};

export function formatCategory(category: ProfileCategory | null): string | null {
  if (!category) return null;
  return categoryLabels[category] || null;
}

// Category-inferred highlights removed — now generated by lib/provider-highlights.ts

// ============================================================
// Category-inferred description (fallback when provider_description is null)
// ============================================================

const categoryDescriptionTemplates: Record<ProfileCategory, (name: string, location: string | null) => string> = {
  home_care_agency: (name, loc) =>
    `${name} is a home care agency${loc ? ` serving the ${loc} area` : ""}. They provide non-medical in-home care services including personal care assistance, companionship, meal preparation, and light housekeeping to help seniors and individuals live safely and comfortably at home.`,
  home_health_agency: (name, loc) =>
    `${name} is a home health agency${loc ? ` serving the ${loc} area` : ""}. They provide skilled medical services in the home including nursing care, physical therapy, occupational therapy, and health monitoring under the direction of a physician.`,
  hospice_agency: (name, loc) =>
    `${name} is a hospice care provider${loc ? ` serving the ${loc} area` : ""}. They offer compassionate end-of-life care focused on comfort, pain management, emotional support, and family counseling for patients and their loved ones.`,
  inpatient_hospice: (name, loc) =>
    `${name} is an inpatient hospice facility${loc ? ` in ${loc}` : ""}. They provide round-the-clock hospice care in a comfortable facility setting, offering pain management, symptom control, emotional support, and family services.`,
  assisted_living: (name, loc) =>
    `${name} is an assisted living community${loc ? ` in ${loc}` : ""}. They offer a supportive residential environment with personal care assistance, medication management, meals, housekeeping, and social activities for seniors who need help with daily living.`,
  memory_care: (name, loc) =>
    `${name} is a memory care community${loc ? ` in ${loc}` : ""}. They provide specialized care for individuals living with Alzheimer's disease and other forms of dementia in a secure, structured environment with trained staff and cognitive support programs.`,
  independent_living: (name, loc) =>
    `${name} is an independent living community${loc ? ` in ${loc}` : ""}. They offer maintenance-free residential living with amenities including dining, housekeeping, social activities, fitness programs, and transportation for active seniors.`,
  nursing_home: (name, loc) =>
    `${name} is a skilled nursing facility${loc ? ` in ${loc}` : ""}. They provide 24-hour nursing care, rehabilitation services, medication management, and personal care for residents who require ongoing medical supervision and support.`,
  rehab_facility: (name, loc) =>
    `${name} is a rehabilitation facility${loc ? ` in ${loc}` : ""}. They offer physical therapy, occupational therapy, speech therapy, and other rehabilitation services to help patients recover strength, mobility, and independence after illness, injury, or surgery.`,
  adult_day_care: (name, loc) =>
    `${name} is an adult day care center${loc ? ` in ${loc}` : ""}. They provide daytime supervision, social activities, meals, health monitoring, and therapeutic programs for seniors and adults who need assistance during the day.`,
  wellness_center: (name, loc) =>
    `${name} is a wellness center${loc ? ` in ${loc}` : ""}. They offer health and fitness programs, wellness education, preventive screenings, and community activities designed to support healthy aging and overall well-being.`,
  private_caregiver: (name, loc) =>
    `${name} is a private caregiver${loc ? ` serving the ${loc} area` : ""}. They provide one-on-one personal care, companionship, meal preparation, light housekeeping, and assistance with daily activities to help individuals maintain their independence at home.`,
};

export function getCategoryDescription(
  category: ProfileCategory,
  providerName: string,
  location: string | null,
): string {
  const template = categoryDescriptionTemplates[category];
  return template ? template(providerName, location) : "";
}

// ============================================================
// Category-inferred care services (used when real data is sparse)
// ============================================================

const categoryServices: Record<ProfileCategory, string[]> = {
  home_care_agency: [
    "Personal care assistance", "Bathing and grooming", "Meal preparation",
    "Medication reminders", "Light housekeeping", "Companionship",
    "Transportation services", "Mobility assistance", "Errands and shopping",
  ],
  home_health_agency: [
    "Skilled nursing", "Physical therapy", "Occupational therapy",
    "Medication management", "Wound care", "Health monitoring",
    "Speech therapy", "IV therapy", "Patient education",
  ],
  hospice_agency: [
    "Pain management", "Nursing care", "Emotional support",
    "Spiritual counseling", "Family support", "Bereavement services",
    "Medication management", "Respite care", "Comfort care",
  ],
  inpatient_hospice: [
    "24-hour nursing care", "Pain management", "Symptom management",
    "Emotional support", "Spiritual counseling", "Family support",
    "Bereavement services", "Comfort care", "Medication management",
  ],
  assisted_living: [
    "Personal care assistance", "Medication management", "Meals and dining",
    "Housekeeping and laundry", "Social activities", "Transportation",
    "Exercise and wellness", "Health monitoring", "Emergency response",
  ],
  memory_care: [
    "Cognitive stimulation", "Personal care assistance", "Medication management",
    "Structured daily activities", "Secure environment", "Meals and dining",
    "Behavioral support", "Health monitoring", "Family education",
  ],
  independent_living: [
    "Meals and dining", "Housekeeping", "Social activities",
    "Fitness and wellness", "Transportation", "Community events",
    "Maintenance services", "Recreational programs", "Concierge services",
  ],
  nursing_home: [
    "Skilled nursing", "Medication management", "Physical therapy",
    "Occupational therapy", "Meals and dining", "Personal care assistance",
    "Social activities", "Wound care", "Rehabilitation services",
  ],
  rehab_facility: [
    "Physical therapy", "Occupational therapy", "Speech therapy",
    "Pain management", "Skilled nursing", "Mobility training",
    "Strength conditioning", "Post-surgical care", "Patient education",
  ],
  adult_day_care: [
    "Social activities", "Health monitoring", "Meals and snacks",
    "Exercise programs", "Cognitive activities", "Personal care assistance",
    "Medication management", "Transportation", "Therapeutic recreation",
  ],
  wellness_center: [
    "Exercise programs", "Health screenings", "Nutrition counseling",
    "Fitness classes", "Wellness education", "Social activities",
    "Stress management", "Balance and fall prevention", "Community programs",
  ],
  private_caregiver: [
    "Personal care assistance", "Companionship", "Meal preparation",
    "Light housekeeping", "Medication reminders", "Transportation",
    "Mobility assistance", "Errands and shopping", "Overnight care",
  ],
};

export function getCategoryServices(category: ProfileCategory): string[] {
  return categoryServices[category] ?? [];
}

// ============================================================
// Quick Facts builder
// ============================================================

export interface QuickFact {
  label: string;
  value: string;
  icon: "category" | "location" | "calendar" | "users" | "award" | "shield" | "dollar";
}

interface QuickFactsInput {
  yearFounded?: number;
  bedCount?: number;
  yearsExperience?: number;
  acceptsMedicaid?: boolean;
  acceptsMedicare?: boolean;
  backgroundChecked?: boolean;
  licensed?: boolean;
}

export function buildQuickFacts(input: QuickFactsInput): QuickFact[] {
  const facts: QuickFact[] = [];

  if (input.yearFounded) {
    const yearsInBusiness = new Date().getFullYear() - input.yearFounded;
    facts.push({ label: "Founded", value: `Est. ${input.yearFounded} (${yearsInBusiness} yrs)`, icon: "calendar" });
  }

  if (input.bedCount) {
    facts.push({ label: "Capacity", value: `${input.bedCount} beds`, icon: "users" });
  }

  if (input.yearsExperience) {
    facts.push({ label: "Experience", value: `${input.yearsExperience} years`, icon: "award" });
  }

  if (input.acceptsMedicare || input.acceptsMedicaid) {
    const types = [];
    if (input.acceptsMedicare) types.push("Medicare");
    if (input.acceptsMedicaid) types.push("Medicaid");
    facts.push({ label: "Insurance", value: types.join(" & "), icon: "shield" });
  }

  if (input.backgroundChecked) {
    facts.push({ label: "", value: "Background Checked", icon: "shield" });
  }

  if (input.licensed) {
    facts.push({ label: "", value: "Licensed & Insured", icon: "award" });
  }

  return facts;
}

// ============================================================
// Default Q&A (category-aware)
// ============================================================

export interface QAItem {
  question: string;
  answer: string;
}

export function getDefaultQA(
  category: ProfileCategory | null,
  providerName: string
): QAItem[] {
  const faqs: QAItem[] = [
    {
      question: `What should I expect during my first visit to ${providerName}?`,
      answer:
        "We encourage families to schedule a tour to see our community firsthand. During your visit, you'll meet our care team, see available living spaces, and learn about our daily programs and activities.",
    },
    {
      question: "What is included in the monthly cost?",
      answer:
        "Our base fee typically covers housing, meals, housekeeping, and basic care services. Additional services such as medication management or specialized care programs may have additional fees. Contact us for a detailed breakdown.",
    },
    {
      question: "How do you handle medical emergencies?",
      answer:
        "Our staff is trained in emergency response protocols. We maintain 24/7 on-call medical support and have established relationships with local hospitals and emergency services for immediate care when needed.",
    },
  ];

  // Add category-specific questions
  if (category === "memory_care") {
    faqs.push({
      question: "What specialized memory care programs do you offer?",
      answer:
        "We offer evidence-based memory care programs including cognitive stimulation therapy, reminiscence activities, and structured daily routines designed to support individuals living with Alzheimer's and other forms of dementia.",
    });
  } else if (category === "home_care_agency" || category === "home_health_agency") {
    faqs.push({
      question: "How are your caregivers screened and trained?",
      answer:
        "All caregivers undergo thorough background checks, reference verification, and skills assessments. They receive ongoing training in areas including fall prevention, medication management, and dementia care techniques.",
    });
  } else if (category === "hospice_agency" || category === "inpatient_hospice") {
    faqs.push({
      question: "What support do you provide for family members?",
      answer:
        "We offer comprehensive family support including counseling, bereavement services, respite care, and educational resources. Our social workers and chaplains are available to help families navigate this journey.",
    });
  } else if (category === "independent_living") {
    faqs.push({
      question: "Can residents personalize their living spaces?",
      answer:
        "Yes, we encourage residents to bring personal belongings, furniture, and decorations to make their space feel like home. Our team can help with the transition and setup.",
    });
  }

  return faqs;
}

// ============================================================
// Suggested Q&A questions (category-specific)
// ============================================================

/**
 * Returns 4-5 emotionally resonant suggested questions for the Q&A section,
 * tailored to the provider's category. These are the primary UI element
 * when a provider has 0 existing questions.
 */
export function getSuggestedQuestions(
  category: ProfileCategory | null
): string[] {
  switch (category) {
    case "home_care_agency":
      return [
        "Can I meet the caregiver before they start?",
        "What happens if my caregiver calls in sick?",
        "Do you have a minimum number of hours per visit?",
        "Are your caregivers background-checked?",
        "Can caregivers help with medication reminders?",
      ];

    case "home_health_agency":
      return [
        "Does Medicare cover your services?",
        "How quickly can a nurse start visiting?",
        "Can you coordinate with my doctor's office?",
        "What happens after my insurance authorization ends?",
        "Do you offer physical therapy at home?",
      ];

    case "hospice_agency":
      return [
        "Is hospice really free for families?",
        "Can my loved one stay at home for hospice?",
        "How quickly can services start?",
        "What support do you offer family caregivers?",
        "What if my loved one improves — can they leave hospice?",
      ];

    case "assisted_living":
      return [
        "Can I tour the community before deciding?",
        "What's included in the monthly cost?",
        "How do you handle medical emergencies?",
        "Can residents bring their own furniture?",
        "What activities and outings do you offer?",
      ];

    case "memory_care":
      return [
        "How do you keep residents with dementia safe?",
        "What's the staff-to-resident ratio?",
        "Can my parent still go outside?",
        "How do you handle sundowning behavior?",
        "What training do your caregivers receive?",
      ];

    case "nursing_home":
      return [
        "Does Medicare or Medicaid cover the stay?",
        "Can I visit anytime?",
        "What's the staff-to-patient ratio?",
        "How do you handle a change in care needs?",
        "What are the options for rehab-to-long-term transitions?",
      ];

    case "independent_living":
      return [
        "What's included in the monthly fee?",
        "Are there options if I need more help later?",
        "What social activities are available?",
        "Can I bring my pet?",
        "Is there a waitlist?",
      ];

    case "inpatient_hospice":
      return [
        "When is inpatient hospice the right choice?",
        "Can family stay overnight?",
        "Is this covered by Medicare?",
        "How is pain managed for patients?",
        "What support do you offer the family?",
      ];

    case "rehab_facility":
      return [
        "How long does the average stay last?",
        "What does a typical day look like?",
        "Will insurance cover my rehab stay?",
        "Can family visit during therapy hours?",
        "What's the transition plan for going home?",
      ];

    case "adult_day_care":
      return [
        "What hours are you open?",
        "Do you offer transportation?",
        "Can you accommodate special dietary needs?",
        "What activities do participants do during the day?",
        "Do you accept Medicaid or VA benefits?",
      ];

    case "wellness_center":
      return [
        "What programs do you offer for seniors?",
        "Do I need a referral to join?",
        "Are group classes available?",
        "What does a first visit look like?",
      ];

    case "private_caregiver":
      return [
        "Are you available on weekends?",
        "Can you help with bathing and personal care?",
        "Do you have experience with dementia patients?",
        "What are your rates?",
        "Can you provide references?",
      ];

    default:
      return [
        "What services do you provide?",
        "What are your rates or pricing?",
        "How quickly can you get started?",
        "Do you accept insurance or Medicaid?",
      ];
  }
}

// ============================================================
// Similar providers (fetched from Supabase)
// ============================================================

// Map ProfileCategory to Supabase provider_category values
const categoryToSupabaseCategory: Record<string, string> = {
  home_care_agency: "Home Care (Non-medical)",
  home_health_agency: "Home Health Care",
  assisted_living: "Assisted Living",
  memory_care: "Memory Care",
  independent_living: "Independent Living",
  nursing_home: "Nursing Home",
  hospice_agency: "Hospice",
  inpatient_hospice: "Hospice",
  rehab_facility: "Nursing Home",
  adult_day_care: "Home Care (Non-medical)",
  wellness_center: "Home Care (Non-medical)",
  private_caregiver: "Home Care (Non-medical)",
};

export async function getSimilarProviders(
  category: ProfileCategory | null,
  excludeSlug: string,
  limit: number = 3
): Promise<Provider[]> {
  if (!category) return [];

  const supabaseCategory = categoryToSupabaseCategory[category];
  if (!supabaseCategory) return [];

  try {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from(PROVIDERS_TABLE)
      .select("*")
      .not("deleted", "is", true)
      .ilike("provider_category", `%${supabaseCategory}%`)
      .neq("provider_id", excludeSlug)
      .not("provider_images", "is", null)
      .order("google_rating", { ascending: false, nullsFirst: false })
      .limit(limit);

    if (error || !data) return [];

    return (data as IOSProvider[]).map(toCardFormat);
  } catch {
    return [];
  }
}
