/**
 * Pipeline drafts for ND — AUTO-GENERATED by scripts/benefits-pipeline.js.
 * Do not edit manually. Regenerated from data/pipeline/ND/drafts.json
 * after each pipeline run for this state, or via --regen-index.
 *
 * Last updated: 2026-04-19T10:13:23.913Z
 */
import type { PipelineStateDrafts } from "../../pipeline-drafts-types";

export const drafts: PipelineStateDrafts = {
  "draftedAt": "2026-04-13",
  "programs": [
    {
      "id": "basic-care-assistance-program",
      "name": "North Dakota Basic Care Assistance Program (BCAP)",
      "shortName": "BCAP",
      "tagline": "Helps cover the cost of basic care facility services for eligible North Dakota seniors and disabled adults.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Customer Support Center (statewide)",
            "type": "service-area"
          },
          {
            "name": "County social workers for assessments",
            "type": "service-area"
          },
          {
            "name": "Licensed basic care facilities statewide",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent needs help with daily activities like bathing, dressing, or eating and lives in a licensed basic care facility, North Dakota's Basic Care Assistance Program (BCAP) may help cover facility costs. BCAP pays a portion of basic care facility expenses for people who qualify for North Dakota Medicaid and need assistance with activities of daily living. Your parent keeps $150 per month for personal needs, while their other income goes toward facility costs and BCAP covers the remaining expenses directly to the facility.\n\nTo qualify, your parent must be 65+ (or 18+ if blind or disabled), meet North Dakota Medicaid income and asset requirements (typically $3,000 asset limit for singles), and pass a functional assessment showing they need help with daily activities. Because this program requires living in a licensed basic care facility, it's designed for people who cannot safely remain at home even with assistance.\n\nBCAP is administered through the same system as Medicaid, so if your parent already receives Medicaid long-term care services, the eligibility process may be streamlined through redetermination rather than a completely new application.",
      "savingsRange": "",
      "savingsSource": "Varies by income - program covers facility costs beyond what recipient can pay",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 65+ or 18+ if blind/disabled",
          "Must qualify for North Dakota Medicaid",
          "Need help with daily activities (bathing, dressing, eating)",
          "Must live in licensed basic care facility",
          "North Dakota resident"
        ],
        "ageRequirement": "65+",
        "incomeTable": null,
        "assetLimits": {
          "individual": 3000,
          "couple": null,
          "countedAssets": [],
          "exemptAssets": [],
          "homeEquityCap": null
        },
        "functionalRequirement": "Must need assistance with activities of daily living such as bathing, dressing, eating, or toileting as determined by functional assessment",
        "otherRequirements": [
          "North Dakota resident",
          "Must qualify for North Dakota Medicaid",
          "Must reside in a licensed basic care facility"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Apply online through North Dakota's Customer Support Center or call (866) 614-6005 - eligibility begins on your application date if qualified.",
        "steps": [
          {
            "step": 1,
            "title": "Check Medicaid eligibility first",
            "description": "Since BCAP requires North Dakota Medicaid qualification, ensure your parent meets Medicaid income and asset requirements. If already on Medicaid, this may be handled through redetermination."
          },
          {
            "step": 2,
            "title": "Submit application",
            "description": "Apply online through the Customer Support Center's Apply for Assistance portal, call (866) 614-6005, or email applyforhelp@nd.gov. You can also mail forms to Customer Support Center, P.O. Box 5562, Bismarck, ND 58506."
          },
          {
            "step": 3,
            "title": "Complete functional assessment",
            "description": "A county social worker will conduct a Personal Care Services Assessment to determine if your parent needs help with activities of daily living like bathing, dressing, or eating."
          },
          {
            "step": 4,
            "title": "Ensure facility placement",
            "description": "Your parent must reside in a licensed basic care facility in North Dakota. Contact agingbcreferrals@nd.gov for assistance with facility referrals."
          }
        ],
        "processingTime": "Eligibility begins on the date of application if qualified",
        "waitlist": null,
        "tip": "If your parent is already receiving Medicaid long-term care services, the BCAP application may be processed through redetermination, which can be faster than a new application.",
        "urls": [
          {
            "label": "Apply for Assistance Online",
            "url": "https://www.hhs.nd.gov/adults-and-aging/services/basic-care-assistance-program-bcap"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security number for applicant",
        "Proof of age (birth certificate or other official document)",
        "Proof of North Dakota residency (utility bill, lease, or state-issued document)",
        "Proof of disability documentation (if under age 65)",
        "Financial information for Medicaid eligibility determination",
        "Bank statements for all accounts",
        "Income documentation (Social Security award letters, pension statements)",
        "Asset documentation (property deeds, vehicle titles, investment accounts)",
        "Health insurance information",
        "Contact information for current healthcare providers",
        "Information about current living situation and care needs"
      ],
      "contacts": [
        {
          "label": "Customer Support Center",
          "phone": "(866) 614-6005",
          "description": "Primary application line for BCAP and Medicaid",
          "hours": "Business hours"
        },
        {
          "label": "Aging and Disability Resource Link (ADRL)",
          "phone": null,
          "description": "Contact agingbcreferrals@nd.gov for basic care facility referrals",
          "hours": "Business hours"
        },
        {
          "label": "Application Email",
          "phone": null,
          "description": "Email applications to applyforhelp@nd.gov",
          "hours": "Business hours"
        }
      ],
      "applicationNotes": [
        "If your parent already receives North Dakota Medicaid, BCAP eligibility may be processed through redetermination rather than a new application",
        "Some applicants may need to have resided in a nursing facility for at least 6 months before qualifying for BCAP if they don't meet nursing facility level of care",
        "The functional assessment must show need for help with activities of daily living - personal care assessment alone may not be sufficient",
        "Eligibility is tied directly to North Dakota Medicaid requirements, so ensuring Medicaid qualification is the first critical step"
      ],
      "relatedPrograms": [
        "North Dakota Medicaid",
        "Supplemental Security Income (SSI)",
        "Medicare Savings Programs",
        "SNAP (Food Assistance)"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my parent apply for BCAP if they're already receiving North Dakota Medicaid?",
          "answer": "Yes, if your parent already receives North Dakota Medicaid, BCAP eligibility may be processed through redetermination rather than requiring a completely new application. Contact the Customer Support Center at (866) 614-6005 to discuss the specific process for current Medicaid recipients."
        },
        {
          "question": "What's the difference between basic care facilities and nursing homes for BCAP eligibility?",
          "answer": "BCAP specifically covers costs for licensed basic care facilities, not nursing homes. Basic care facilities provide assistance with activities of daily living but offer less intensive medical care than nursing facilities. Some applicants may need to have resided in a nursing facility for at least 6 months before qualifying for BCAP in certain circumstances."
        },
        {
          "question": "How much of my parent's income will go toward facility costs?",
          "answer": "Your parent keeps $150 per month for personal needs. All other income must be applied toward facility costs and medical expenses, with BCAP covering the remaining facility expenses directly. The exact amount BCAP pays depends on your parent's total income and the facility's costs."
        },
        {
          "question": "What if my parent needs nursing home level care but wants to try basic care first?",
          "answer": "This requires careful coordination with healthcare providers and the county social worker doing the functional assessment. The assessment must show that basic care facility services are appropriate for your parent's needs. Contact agingbcreferrals@nd.gov to discuss facility options and care level requirements."
        },
        {
          "question": "Can I apply for BCAP on behalf of my elderly parent?",
          "answer": "Yes, family members can typically apply on behalf of elderly parents, especially if the parent has cognitive impairment or difficulty managing paperwork. You may need to provide documentation of your authority to act on their behalf, such as power of attorney documents."
        },
        {
          "question": "What happens if my parent's care needs increase while on BCAP?",
          "answer": "If your parent's care needs change significantly, they'll need a new functional assessment. This could result in a recommendation for a different level of care, such as nursing facility placement, which would involve transitioning to different Medicaid long-term care services."
        },
        {
          "question": "Are there any assets my parent can keep while on BCAP?",
          "answer": "BCAP follows North Dakota Medicaid asset rules, which typically allow $3,000 in countable assets for single individuals. However, specific exemptions and rules for what counts as assets aren't detailed in BCAP program materials - contact the Customer Support Center at (866) 614-6005 for specific guidance about your parent's assets."
        },
        {
          "question": "What if there are no licensed basic care facilities available in my parent's area?",
          "answer": "Contact agingbcreferrals@nd.gov for assistance finding available licensed basic care facilities statewide. While your parent must be a North Dakota resident, they don't necessarily need to stay in their current community if appropriate facilities aren't available locally."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "asset-focused",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "Bed",
      "phone": "(866) 614-6005",
      "sourceUrl": "https://www.hhs.nd.gov/adults-and-aging/services/basic-care-assistance-program-bcap",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "aging-in-community-project",
      "name": "North Dakota Aging in Community (AIC) Project",
      "shortName": "AIC Project",
      "tagline": "Community volunteers help your parent stay safely at home in rural North Dakota — transportation, fall prevention, and local connections.",
      "programType": "benefit",
      "complexity": "medium",
      "geographicScope": {
        "type": "local",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "NDSU Extension Service (Lisbon, western Morton Counties)",
            "type": "service-area"
          },
          {
            "name": "Local community partners and volunteers",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent lives in rural North Dakota and wants to stay at home but needs help with transportation, learning about technology, or connecting with local resources, the Aging in Community Project may provide volunteer assistance at no cost. Because this is a community-based pilot program, it's only available in select rural areas like Lisbon and western Morton Counties.\n\nThe program focuses on practical daily support — volunteer drivers for medical appointments, nutrition and fall prevention classes, help learning to use smartphones or tablets, and connections to other local services. Because it relies on volunteers and local partnerships rather than paid staff, the specific services vary by location but all aim to help older adults remain safely independent in their rural homes.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "North Dakota resident",
          "Living in targeted rural communities",
          "Desire to age in place at home"
        ],
        "ageRequirement": "60+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "North Dakota resident",
          "Living in implementation areas such as Lisbon and western Morton Counties",
          "Desire to remain living independently at home"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Contact NDSU Extension Service in your area to connect with local AIC project coordinators — no formal application required.",
        "steps": [
          {
            "step": 1,
            "title": "Check if your area is served",
            "description": "Confirm your parent lives in an active AIC project area like Lisbon or western Morton Counties by visiting ndsu.edu/agriculture/extension."
          },
          {
            "step": 2,
            "title": "Contact NDSU Extension",
            "description": "Call your local NDSU Extension office to connect with AIC project coordinators who can explain available volunteer services in your specific community."
          },
          {
            "step": 3,
            "title": "Meet with local coordinator",
            "description": "A local coordinator will assess your parent's needs and interests, then match them with appropriate volunteer assistance and community resources."
          },
          {
            "step": 4,
            "title": "Begin services",
            "description": "Start receiving volunteer support for transportation, classes, or technology help based on what's available in your community and your parent's preferences."
          }
        ],
        "processingTime": "Not specified",
        "waitlist": null,
        "tip": "Because services depend on local volunteers, ask specifically what's currently available in your parent's community — offerings can change based on volunteer capacity.",
        "urls": [
          {
            "label": "NDSU Extension Programs",
            "url": "https://www.ndsu.edu/agriculture/extension/programs/aging-community-program"
          }
        ]
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "NDSU Extension Service",
          "phone": null,
          "description": "Contact your local NDSU Extension office to connect with AIC project coordinators",
          "hours": "Varies by office"
        },
        {
          "label": "North Dakota 2-1-1",
          "phone": "2-1-1",
          "description": "General information about aging services and community resources",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "This is a pilot program in select rural communities only — not available statewide",
        "Services depend on local volunteer availability and may vary by season or community capacity",
        "Success is measured in community connections and confidence building rather than guaranteed hours of service"
      ],
      "relatedPrograms": [
        "North Dakota SPED (Service Payments for Elderly and Disabled)",
        "Area Agencies on Aging services",
        "North Dakota Meals on Wheels"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Is this program available where my parent lives?",
          "answer": "The AIC Project operates only in select rural communities like Lisbon and western Morton Counties. Contact your local NDSU Extension office to confirm if your parent's area is served, as this is a pilot program with limited geographic reach."
        },
        {
          "question": "What if my parent needs more intensive help than volunteers can provide?",
          "answer": "The AIC Project focuses on community connections and prevention rather than medical care or intensive daily assistance. If your parent needs help with bathing, medication management, or clinical care, ask the coordinator about referrals to programs like SPED or Medicaid waiver services."
        },
        {
          "question": "Can my parent count on regular transportation every week?",
          "answer": "Transportation depends on volunteer driver availability in your specific community, so it may not be as reliable as paid services. Ask the local coordinator about typical availability and consider this as supplemental to other transportation arrangements."
        },
        {
          "question": "How is this different from other aging services in North Dakota?",
          "answer": "Unlike SPED (which pays for services) or Medicaid waivers (which provide clinical care), the AIC Project uses volunteers to build community connections and teach practical skills. It's designed to prevent isolation and help people stay independent longer, not replace medical services."
        },
        {
          "question": "What happens if my parent moves to a different rural town?",
          "answer": "If your parent moves outside an active AIC project area, they would no longer be eligible for services. The program is location-specific and depends on local volunteer networks and NDSU Extension partnerships in each community."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": false,
        "visualTone": "warm"
      },
      "icon": "Users",
      "phone": null,
      "sourceUrl": "https://www.ndsu.edu/agriculture/extension/programs/aging-community-program",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    },
    {
      "id": "assistive-senior-safety-program",
      "name": "ND Assistive Senior Safety Program",
      "shortName": "Senior Safety Program",
      "tagline": "Free safety devices and professional setup to help your parent stay safely at home",
      "programType": "resource",
      "complexity": "simple",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Central office: 3240 15th St. S, Suite B, Fargo, ND 58104",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your parent is 60+ and needs safety devices to remain at home, North Dakota provides free assistive equipment with professional installation. The program covers alerting devices for hearing loss, anti-elopement devices for dementia care, and other home safety equipment — plus setup assistance to ensure everything works properly.\n\nThis is a last-resort program — your parent must first be denied coverage through insurance, Medicare, or Medicaid. Because the program prioritizes requests, you'll rank devices in order of importance on your application. Income guidelines apply, but specific limits are detailed in the current year's application form.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "North Dakota resident",
          "Income guidelines apply",
          "Need safety devices to remain at home",
          "Not covered by insurance/Medicare/Medicaid"
        ],
        "ageRequirement": "60+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": "Must need assistive safety devices to remain safely in home",
        "otherRequirements": [
          "North Dakota resident",
          "Does not qualify for devices through insurance, Medicare, Medicaid, or other programs"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Apply online or by mail with proof of income and device needs — typically takes 3-4 weeks to process.",
        "steps": [
          {
            "step": 1,
            "title": "Get the application",
            "description": "Apply online at ndassistive.org/senior-safety-program/asdds-application/ or download the PDF form (large print version available)"
          },
          {
            "step": 2,
            "title": "List devices in priority order",
            "description": "Rank the safety devices you need most — only one device per line on the application"
          },
          {
            "step": 3,
            "title": "Gather required documents",
            "description": "Include proof of income, documentation of need, and proof you don't qualify for coverage elsewhere"
          },
          {
            "step": 4,
            "title": "Submit application",
            "description": "Mail to ND Assistive/ Senior Safety, 3240 15th St. S, Suite B, Fargo, ND 58104 or fax to 701-365-6242"
          }
        ],
        "processingTime": "Typically 3-4 weeks",
        "waitlist": null,
        "tip": "List devices in order of importance — the program may not approve everything you request, so prioritize what your parent needs most.",
        "urls": [
          {
            "label": "Online Application",
            "url": "https://ndassistive.org/senior-safety-program/asdds-application/"
          },
          {
            "label": "Download PDF Form",
            "url": "https://ndassistive.org/wp-content/uploads/2025/03/2025-Senior-Safety-Application-Standard-Print.pdf"
          }
        ]
      },
      "documentsNeeded": [
        "Completed Senior Safety Application with devices ranked in order of importance",
        "Proof of income to meet program guidelines",
        "Documentation of residency in North Dakota",
        "Documentation showing need for assistive safety devices",
        "Proof of denial or non-qualification from insurance, Medicare, Medicaid, or other funding sources"
      ],
      "contacts": [
        {
          "label": "Senior Safety Program",
          "phone": "(800) 735-5400",
          "description": "Questions about applications and device availability",
          "hours": "Business hours"
        },
        {
          "label": "Program Email",
          "phone": null,
          "description": "Email questions to seniorsafety@ndassistive.org",
          "hours": null
        }
      ],
      "applicationNotes": null,
      "relatedPrograms": [
        "North Dakota Weatherization Program",
        "North Dakota Energy Assistance Program",
        "Area Agency on Aging Services"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "What if my parent lives in assisted living — can they still get these devices?",
          "answer": "Yes, the program is available to seniors in assisted living facilities if they need additional safety devices beyond what the facility provides. The application process is the same."
        },
        {
          "question": "Can I apply if my parent was denied by Medicare but we haven't tried Medicaid yet?",
          "answer": "No — you must exhaust all other funding sources first, including Medicaid. The Senior Safety Program only serves as a last resort when insurance, Medicare, Medicaid, and other programs won't cover the devices."
        },
        {
          "question": "How many devices can my parent receive through this program?",
          "answer": "The application doesn't specify a limit, but you must rank devices in order of importance because the program may not approve everything you request. Priority is given based on safety need and available funding."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": null,
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "step-journey",
        "hasLocationFinder": false,
        "hasDocumentChecklist": true,
        "visualTone": "minimal"
      },
      "icon": "House",
      "phone": "(800) 735-5400",
      "sourceUrl": "https://ndassistive.org/senior-safety-program/asdds-application/",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-04-13"
    }
  ],
  "stateOverview": {
    "intro": "North Dakota offers 3 key programs to help your aging parent stay safe and supported. Two provide direct financial assistance for care services, while one offers free safety resources for any North Dakota senior. The Basic Care Assistance Program helps cover facility care costs, the Aging in Community Project provides volunteer support specifically in rural areas, and the Assistive Senior Safety Program delivers free safety devices with professional installation. Start by identifying your parent's most immediate need — whether that's paying for care, staying connected in a rural community, or making their home safer.",
    "startHere": [
      {
        "name": "ND Assistive Senior Safety Program",
        "programId": "assistive-senior-safety-program",
        "why": "No income requirements and provides immediate safety improvements with free professional installation."
      },
      {
        "name": "North Dakota Aging in Community (AIC) Project",
        "programId": "north-dakota-aging-in-community-aic-project",
        "why": "Specifically designed for rural North Dakota seniors who want to stay home with community volunteer support."
      },
      {
        "name": "North Dakota Basic Care Assistance Program (BCAP)",
        "programId": "north-dakota-basic-care-assistance-program-bcap",
        "why": "Provides direct financial help for facility care when your parent needs more support than home-based options can provide."
      }
    ],
    "byNeed": [
      {
        "need": "Help paying for care facility services",
        "programs": [
          "North Dakota Basic Care Assistance Program (BCAP)"
        ],
        "description": "Financial assistance for basic care facility costs for eligible seniors and disabled adults."
      },
      {
        "need": "Support staying at home in rural areas",
        "programs": [
          "North Dakota Aging in Community (AIC) Project"
        ],
        "description": "Community volunteers provide transportation, fall prevention, and local connections specifically for rural North Dakota."
      },
      {
        "need": "Free home safety improvements",
        "programs": [
          "ND Assistive Senior Safety Program"
        ],
        "description": "Safety devices and professional installation at no cost to help prevent falls and accidents."
      }
    ],
    "quickFacts": [
      "North Dakota focuses heavily on rural aging support through volunteer-based community programs",
      "The state offers both income-qualified benefits and universal free safety resources",
      "Two programs require eligibility screening while one is available to all North Dakota seniors"
    ],
    "resourcesVsBenefits": "North Dakota offers both types of help: qualification-based benefits like BCAP that require income and asset screening to help pay for care, and free resources like the Assistive Senior Safety Program that any North Dakota senior can access regardless of income. The AIC Project falls in between — it's free but specifically serves rural communities where volunteer networks are available."
  }
};
