"use client";

const CHECKLIST_CATEGORIES = [
  {
    name: "Identity & Personal",
    items: [
      "Government-issued photo ID",
      "Social Security card",
      "Birth certificate",
      "Marriage certificate (if applicable)",
      "Passport-size photo",
    ],
  },
  {
    name: "Medical & Health",
    items: [
      "Medical records or doctor's statement",
      "Diagnosis or disability documentation",
      "Current medication list",
      "Health insurance card (Medicare/Medicaid)",
    ],
  },
  {
    name: "Financial & Income",
    items: [
      "Proof of income (pay stubs, tax return, SSI letter)",
      "Bank statements (last 3 months)",
      "Proof of assets (property, investments)",
      "Proof of expenses (rent, utilities, medical bills)",
    ],
  },
  {
    name: "Residency & Housing",
    items: [
      "Proof of state residency (utility bill, lease)",
      "Current living arrangement documentation",
      "Proof of U.S. citizenship or immigration status",
    ],
  },
];

export function DownloadChecklistButton() {
  function handleDownload() {
    let text = "BENEFITS APPLICATION — DOCUMENT CHECKLIST\n";
    text += "==========================================\n\n";

    for (const category of CHECKLIST_CATEGORIES) {
      text += `${category.name.toUpperCase()}\n`;
      text += "-".repeat(category.name.length) + "\n";
      for (const item of category.items) {
        text += `[ ] ${item}\n`;
      }
      text += "\n";
    }

    text += "---\nGenerated by Olera (olera.care)\n";

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "benefits-document-checklist.txt";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center gap-1.5 px-4 py-2 bg-primary-600 text-white text-sm font-semibold rounded-xl hover:bg-primary-700 transition-colors"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
      </svg>
      Download full checklist
    </button>
  );
}
