/**
 * Pipeline exploration summary — AUTO-GENERATED by benefits-pipeline.js
 * Do not edit manually. Regenerated after each pipeline run.
 *
 * Last updated: 2026-04-08T16:04:08.780Z
 */

export interface PipelineDiff {
  field: string;
  ours: string;
  found: string;
  source?: string;
}

export interface PipelineComparison {
  name: string;
  isNew: boolean;
  existingId: string | null;
  diffsFound: number;
  diffs: PipelineDiff[];
  novelFields: { field: string; note: string }[];
}

export interface PipelineClassification {
  types: Record<string, number>;
  scopes: Record<string, number>;
  complexity: Record<string, number>;
}

export interface PipelineStateSummary {
  exploredAt: string;
  programsFound: number;
  newPrograms: number;
  diffsFound: number;
  novelFieldCount: number;
  comparisons: PipelineComparison[];
  classifiedAt?: string;
  classification?: PipelineClassification;
  draftedAt?: string;
  draftsGenerated?: number;
  draftsTotal?: number;
}

export const pipelineData: Record<string, PipelineStateSummary> = {
  "MI": {
    "exploredAt": "2026-04-07",
    "programsFound": 16,
    "newPrograms": 12,
    "diffsFound": 4,
    "novelFieldCount": 5,
    "comparisons": [
      {
        "name": "Medicare Savings Programs (MSP) - QMB, SLMB, QI",
        "isNew": false,
        "existingId": "medicare-savings-program",
        "diffsFound": 1,
        "diffs": [
          {
            "field": "source_url",
            "ours": "MISSING",
            "found": "https://www.michigan.gov/mdhhs/assistance-programs/healthcare/disabilities/dualeligible/medicare-sav..."
          }
        ],
        "novelFields": [
          {
            "field": "asset_limits",
            "note": "Our model has no asset limit fields"
          },
          {
            "field": "regional_variations",
            "note": "Program varies by region — our model doesn't capture this"
          },
          {
            "field": "waitlist",
            "note": "Has waitlist info — our model has no wait time field"
          },
          {
            "field": "documents_required",
            "note": "Has document checklist — our model doesn't store per-program documents"
          }
        ]
      },
      {
        "name": "SNAP Food Assistance (MiCAFE for seniors)",
        "isNew": false,
        "existingId": "food-assistance-program",
        "diffsFound": 3,
        "diffs": [
          {
            "field": "min_age",
            "ours": "65",
            "found": "60",
            "source": "https://www.michigan.gov/mdhhs/assistance-programs/food"
          },
          {
            "field": "benefit_value",
            "ours": "$1,500 – $3,600/year",
            "found": "SNAP benefits via Michigan Bridge Card for purchasing food at grocery stores, supermarkets, farmers ...",
            "source": "https://www.michigan.gov/mdhhs/assistance-programs/food"
          },
          {
            "field": "source_url",
            "ours": "MISSING",
            "found": "https://www.michigan.gov/mdhhs/assistance-programs/food"
          }
        ],
        "novelFields": [
          {
            "field": "asset_limits",
            "note": "Our model has no asset limit fields"
          },
          {
            "field": "household_size_table",
            "note": "Benefits/eligibility vary by household size — we store a single number"
          },
          {
            "field": "regional_variations",
            "note": "Program varies by region — our model doesn't capture this"
          },
          {
            "field": "documents_required",
            "note": "Has document checklist — our model doesn't store per-program documents"
          }
        ]
      },
      {
        "name": "Nursing Home Long-Term Care Ombudsman",
        "isNew": false,
        "existingId": "long-term-care-ombudsman-program",
        "diffsFound": 2,
        "diffs": [
          {
            "field": "benefit_value",
            "ours": "$10,000 – $30,000/year",
            "found": "Free, confidential advocacy services including investigating and resolving complaints about care or ...",
            "source": "https://mltcop.org"
          },
          {
            "field": "source_url",
            "ours": "MISSING",
            "found": "https://mltcop.org"
          }
        ],
        "novelFields": [
          {
            "field": "asset_limits",
            "note": "Our model has no asset limit fields"
          },
          {
            "field": "regional_variations",
            "note": "Program varies by region — our model doesn't capture this"
          },
          {
            "field": "documents_required",
            "note": "Has document checklist — our model doesn't store per-program documents"
          }
        ]
      },
      {
        "name": "MI Choice Waiver Program",
        "isNew": false,
        "existingId": "mi-choice-waiver-program",
        "diffsFound": 3,
        "diffs": [
          {
            "field": "min_age",
            "ours": "65",
            "found": "65 or older, OR 18+ with documented disability",
            "source": "https://www.michigan.gov/mdhhs/assistance-programs/healthcare/seniors/michoicewaiver"
          },
          {
            "field": "benefit_value",
            "ours": "$10,000 – $30,000/year",
            "found": "Home and community-based services equivalent to nursing home care, including: Nursing Services (Prev...",
            "source": "https://www.michigan.gov/mdhhs/assistance-programs/healthcare/seniors/michoicewaiver"
          },
          {
            "field": "source_url",
            "ours": "MISSING",
            "found": "https://www.michigan.gov/mdhhs/assistance-programs/healthcare/seniors/michoicewaiver"
          }
        ],
        "novelFields": [
          {
            "field": "asset_limits",
            "note": "Our model has no asset limit fields"
          },
          {
            "field": "regional_variations",
            "note": "Program varies by region — our model doesn't capture this"
          },
          {
            "field": "waitlist",
            "note": "Has waitlist info — our model has no wait time field"
          },
          {
            "field": "documents_required",
            "note": "Has document checklist — our model doesn't store per-program documents"
          }
        ]
      }
    ],
    "classifiedAt": "2026-04-08",
    "classification": {
      "types": {
        "benefit": 11,
        "navigator": 2,
        "employment": 1,
        "resource": 2
      },
      "scopes": {
        "local": 3,
        "state": 5,
        "federal": 8
      },
      "complexity": {
        "deep": 11,
        "simple": 4,
        "medium": 1
      }
    },
    "draftedAt": "2026-04-08",
    "draftsGenerated": 16,
    "draftsTotal": 16
  }
};
