# -*- coding: utf-8 -*-
T8_TIMELINE = """
<table class="dat">
<colgroup><col style="width:13%"><col style="width:31%"><col style="width:29%"><col style="width:27%"></colgroup>
<thead><tr><th>Period</th><th>Research and product execution</th><th>Commercialization milestone</th><th>Decision or financing gate</th></tr></thead>
<tbody>
<tr><td><b>Year 1 (CRP)</b><br>Build</td><td>Complete and instrument CareNavigator execution infrastructure; engineer and automate Caregiver Staffing workflows; establish acquisition, outcomes, and county-market measurement systems.</td><td>Technical and measurement infrastructure operational; Staffing workflow ready for real-world deployment; commercialization hypotheses and investor-readiness framework established.</td><td>Confirm readiness for real-world market validation; correct components missing predefined readiness thresholds before scaled deployment.</td></tr>
<tr><td><b>Year 2 (CRP)</b><br>Validate free</td><td>Deploy across selected CRP county markets; test CareNavigator acquisition and execution; provide Staffing free of charge to isolate operational performance from willingness to pay; measure applicant acquisition, qualification, provider interviews, successful hires, retention, care establishment, and longitudinal outcomes.</td><td>Quantify acquisition costs, successful hires per county per month, provider demand and repeat use, geographic replicability, and care-establishment performance; assemble evidence for structured investor cultivation.</td><td>Determine which market and channel configurations advance to paid testing; begin structured investor cultivation and institutional-buyer evidence discussions.</td></tr>
<tr><td><b>Year 3 (CRP)</b><br>Monetize</td><td>Introduce real Staffing pricing and billing; test pricing and packaging; measure willingness to pay, repeat purchase, retention, and contribution economics; independently validate unit economics; complete CareNavigator outcomes and economic evidence package.</td><td>Base planning case: about $120K recognized Staffing revenue and about $240K annualized exit run rate; county-level commercial economics characterized; validated market-entry playbook and institutional evidence package completed.</td><td>Select markets for post-CRP replication; determine institutional contracting readiness; conduct formal third-party financing process and target financing availability before CRP runway ends.</td></tr>
<tr><td><b>Year 4 (post-CRP)</b><br>Expand</td><td>Replicate validated Staffing playbook into additional counties; pursue initial institutional CareNavigator relationships; deploy post-CRP capital; expand market operations and institutional business development.</td><td>Base planning case reaches about $600K combined commercial revenue, with Staffing expansion and initial institutional revenue establishing two complementary commercial pathways.</td><td>Set expansion pace based on measured county economics, institutional traction, available capital, and operating runway.</td></tr>
<tr><td><b>Year 5 (post-CRP)</b><br>Scale</td><td>Continue county replication; mature early institutional relationships; expand workforce, provider-success, and institutional commercial capacity; reinvest revenue alongside growth capital.</td><td>Base planning case reaches about $1.5M combined commercial revenue, approximately 25 Staffing counties, and approximately three institutional relationships, with a validated pathway to broader national replication.</td><td>Scale according to measured economics and capital efficiency as recurring revenue progressively finances a greater share of continued commercialization.</td></tr>
</tbody></table>
<p class="caption"><b>Table 8.</b> Five-year research-to-commercialization management timeline. Years 1 to 3 comprise the CRP period; Years 4 and 5 show the immediate post-CRP commercialization handoff. Revenue values are planning projections rather than CRP success criteria and will be replaced by economics measured during the award.</p>
"""
