-- War Room decision memory.
-- Recommendations are computed from live evidence; this append-only trail
-- records what the team chose so later reviews can judge the decision.

CREATE TABLE IF NOT EXISTS war_room_decisions (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_key    text NOT NULL,
  recommendation_title  text NOT NULL,
  decision              text NOT NULL
    CHECK (decision IN ('backed', 'rejected', 'completed')),
  note                  text,
  decided_by            text NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_war_room_decisions_recent
  ON war_room_decisions (created_at DESC);

ALTER TABLE war_room_decisions ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE war_room_decisions IS
  'Append-only admin decisions on War Room recommendations. Service-role routes own reads and writes.';

CREATE TABLE IF NOT EXISTS war_room_runs (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  status                text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  window_days           integer NOT NULL CHECK (window_days IN (7, 30, 90)),
  requested_by          text NOT NULL,
  model                 text NOT NULL,
  fact_pack             jsonb NOT NULL,
  analyst_draft         jsonb,
  critic_review         jsonb,
  briefing              jsonb,
  citations             jsonb NOT NULL DEFAULT '[]'::jsonb,
  input_tokens          integer,
  output_tokens         integer,
  error_message         text,
  started_at            timestamptz,
  completed_at          timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_war_room_runs_recent
  ON war_room_runs (window_days, created_at DESC);

-- One paid analysis per window at a time. The route marks abandoned runs
-- failed before starting another, and this index closes the two-tab race.
CREATE UNIQUE INDEX IF NOT EXISTS idx_war_room_runs_one_active_window
  ON war_room_runs (window_days)
  WHERE status IN ('queued', 'running');

ALTER TABLE war_room_runs ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE war_room_runs IS
  'Durable evidence snapshots and cited AI briefings generated by the admin War Room.';
