/**
 * Pipeline drafts for PA — AUTO-GENERATED by scripts/benefits-pipeline.js.
 * Do not edit manually. Regenerated from data/pipeline/PA/drafts.json
 * after each pipeline run for this state, or via --regen-index.
 *
 * Last updated: 2026-06-19T09:41:54.992Z
 */
import type { PipelineStateDrafts } from "../../pipeline-drafts-types";

export const drafts: PipelineStateDrafts = {
  "draftedAt": "2026-04-13",
  "programs": [
    {
      "id": "community-healthchoices-chc",
      "name": "Community HealthChoices (CHC)",
      "shortName": "CHC",
      "tagline": "If your loved one needs daily help at home or is dual eligible for Medicare and Medicaid, CHC covers up to 32 services including personal care, home health, and adult day programs.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local AAAs, CAOs, MCOs (choice after approval)",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 21+ and enrolled in both Medicare and Medicaid, or qualifies for Medicaid long-term care due to needing daily help with bathing, dressing, or medication management, Community HealthChoices (CHC) provides comprehensive home and community-based services. Because CHC is a managed care program, your loved one gets coordinated services through one organization instead of juggling multiple providers.\n\nCHC covers a wide range of services—including personal care, home health, attendant care, adult day services, pest eradication, educational support, and nursing facility care if needed. Services are individualized based on your loved one's needs assessment, ensuring the care plan fits their specific situation. As of 2026, the monthly income limit is $2,982 per person, and home equity up to $752,000 is exempt if your loved one lives there or intends to return.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 21+",
          "Pennsylvania resident",
          "Enrolled in Medicaid",
          "Dual eligible OR needs nursing facility level care",
          "Income up to $2,982/month (2026)"
        ],
        "ageRequirement": "21+",
        "incomeTable": null,
        "assetLimits": {
          "individual": 8000,
          "couple": null,
          "countedAssets": [
            "bank accounts",
            "property",
            "retirement accounts"
          ],
          "exemptAssets": [
            "primary home under equity limit",
            "certain personal items"
          ],
          "homeEquityCap": 752000
        },
        "functionalRequirement": "Must need nursing facility level of care (assessment of whether your loved one needs daily help with Activities of Daily Living like bathing, dressing, eating, or transferring)",
        "otherRequirements": [
          "Pennsylvania resident",
          "Enrolled in Medicaid",
          "Dual eligible (Medicare and Medicaid) OR qualify for Medicaid long-term services due to functional need"
        ],
        "povertyLevelReference": "300% of Federal Benefit Rate"
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Call the Pennsylvania Independent Enrollment Broker at 1-877-550-4227 or apply online through COMPASS, screening within 90 days for new dual eligibles.",
        "steps": [
          {
            "step": 1,
            "title": "Submit a Referral",
            "description": "Start by submitting a Community Referral Form to the Pennsylvania Independent Enrollment Broker (PA IEB). You can do this online at paieb.com, by phone at 1-877-550-4227, or by mail."
          },
          {
            "step": 2,
            "title": "Complete Physician Certification",
            "description": "The PA IEB will send a Physician Certification Form to your loved one's doctor. This form must be completed and returned to the PA IEB to verify that your loved one meets the clinical criteria for long-term care services."
          },
          {
            "step": 3,
            "title": "Initial Assessment",
            "description": "An intake specialist from the PA IEB will schedule an in-home visit to discuss your loved one's needs, abilities, and program options. They will also assist with the Medicaid application (such as the PA 600) if your loved one is not already enrolled."
          },
          {
            "step": 4,
            "title": "Functional Eligibility Determination (FED)",
            "description": "After the initial visit, the PA IEB coordinates with the local Area Agency on Aging (AAA) to conduct a Functional Eligibility Determination (FED) assessment. This confirms your loved one meets the level-of-care requirements for home and community-based services."
          },
          {
            "step": 5,
            "title": "Financial Eligibility Review",
            "description": "The County Assistance Office (CAO) reviews the submitted Medicaid application to determine financial eligibility."
          },
          {
            "step": 6,
            "title": "Enrollment",
            "description": "Once both clinical and financial eligibility are confirmed, the CAO will notify you, the PA IEB, and the Managed Care Organization (MCO) you have selected. You will then finalize your enrollment and work with your MCO to select a service coordinator and develop a care plan."
          }
        ],
        "processingTime": "Screening within 90 days for new dual eligibles; comprehensive needs assessment as needed or requested",
        "waitlist": null,
        "tip": "If your loved one is over the income limit, they may still qualify through spend-down if they meet the functional eligibility requirements.",
        "urls": [
          {
            "label": "COMPASS Application",
            "url": "https://www.compass.state.pa.us/"
          },
          {
            "label": "CHC Information",
            "url": "https://www.pa.gov/agencies/dhs/resources/medicaid/chc"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security cards for all household members",
        "Medicare card (both parts A and B)",
        "Current Medicaid card or approval letter",
        "Proof of Pennsylvania residency (utility bill, lease, or state-issued document)",
        "Most recent Social Security award letter",
        "Bank statements for all accounts (last 3 months)",
        "Property deeds and tax statements for real estate owned",
        "Retirement account statements (401k, IRA, pension)",
        "Life insurance policies with cash values",
        "Vehicle titles and registration",
        "Medical records documenting need for daily care assistance",
        "Current medication list and prescribing physician information",
        "Documentation of any other health insurance coverage",
        "Legal documents if someone has power of attorney or guardianship"
      ],
      "contacts": [
        {
          "label": "Pennsylvania Independent Enrollment Broker",
          "phone": "1-877-550-4227",
          "description": "CHC enrollment and managed care organization selection",
          "hours": "Business hours"
        },
        {
          "label": "Pennsylvania 2-1-1",
          "phone": "2-1-1",
          "description": "General assistance finding local County Assistance Office and Area Agency on Aging",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "CHC is mandatory managed care, it replaces prior waiver programs like Aging and Attendant Care waivers",
        "Even if your loved one is dual eligible, they still need to meet functional eligibility requirements through the FED assessment",
        "LIFE program is an alternative for ages 55+ in served areas, you can opt out of CHC to choose LIFE instead",
        "Income and asset limits are reviewed strictly by the County Assistance Office using standard Medicaid rules",
        "To qualify, your loved one's \"countable\" assets must generally be under $8,000 for an individual (if their monthly income is $2,982 or less). If their income is higher, the asset limit is $2,400."
      ],
      "relatedPrograms": [
        "LIFE (Living Independence for the Elderly)",
        "Pennsylvania Medicaid",
        "PACE (Program of All-Inclusive Care for the Elderly)"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my loved one keep their house if it's worth more than the asset limits?",
          "answer": "Yes, your loved one can keep their primary home as long as the equity is under $752,000 in 2026, they live there, intend to return, or a non-applicant spouse or dependent lives there. Home equity above this limit may affect eligibility."
        },
        {
          "question": "What if my loved one has intellectual or developmental disabilities?",
          "answer": "CHC does not cover intellectual or developmental disability services beyond supports coordination. These are handled through the DHS Office of Developmental Programs, which has separate waiver programs."
        },
        {
          "question": "Can my loved one stay in their current nursing home if they're already there?",
          "answer": "If your loved one is in a nursing home paid for by Medicaid, they will be enrolled in Community HealthChoices (CHC). They can generally remain in their current nursing home, provided the facility is in their chosen Managed Care Organization's (MCO) network. CHC does not cover residents in state-operated facilities, such as state veterans' homes, which remain outside the CHC program."
        },
        {
          "question": "How do we choose between different managed care organizations?",
          "answer": "After CHC approval, you'll select an MCO that will coordinate all services. Ask about provider networks, wait times, and specific services your loved one needs. Different MCOs serve different regions and may have varying availability."
        },
        {
          "question": "What happens to my loved one's Medicare benefits under CHC?",
          "answer": "Medicare benefits remain completely separate from CHC. Your loved one keeps their Medicare coverage and providers. CHC only coordinates the Medicaid long-term services and supports."
        },
        {
          "question": "Can I apply for CHC while my loved one is still in the hospital?",
          "answer": "Yes, hospital discharge planners often help initiate the CHC application process. This can help ensure services are in place before your loved one returns home or moves to a care facility."
        },
        {
          "question": "What if my loved one's income is slightly over the $2,982 monthly limit?",
          "answer": "Your loved one may still qualify even if their income exceeds the limit. Pennsylvania offers pathways such as 'spend-down' or specific Medicaid planning strategies (like Qualified Income Trusts) to help applicants who are over the income threshold. The County Assistance Office will determine if their medical expenses can be used to meet eligibility requirements."
        },
        {
          "question": "How often are services reassessed once my loved one is enrolled?",
          "answer": "CHC conducts periodic reassessments based on your loved one's changing needs. You can also request a reassessment if your loved one's condition changes or they need additional services."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "asset-focused",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "House",
      "phone": "1-877-550-4227",
      "sourceUrl": "https://www.pa.gov/agencies/dhs/resources/medicaid/chc",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "life-program",
      "name": "LIFE (Living Independence for the Elderly)",
      "shortName": "LIFE",
      "tagline": "Pennsylvania's all-inclusive care program (the state's PACE): full medical and long-term care so frail seniors 55+ can keep living at home instead of in a nursing facility.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state"
      },
      "intro": "If your loved one is 55 or older, needs nursing-home level of care, but wants to keep living at home, Pennsylvania's LIFE program may cover everything — medical care, prescriptions, in-home help, and more — at little or no cost. LIFE is Pennsylvania's version of the national PACE model (Program of All-Inclusive Care for the Elderly). One provider organization coordinates and pays for all of your loved one's care, so you are not juggling separate doctors, pharmacies, home aides, and insurers.\n\nEverything is built around a local LIFE center your loved one attends as often as their care plan calls for. The team there — doctors, nurses, therapists, social workers, and aides — manages primary and specialty care, prescriptions, physical and occupational therapy, adult day services, personal and home care, meals, dental, vision, hearing, and transportation to the center and to medical appointments. If your loved one ever needs a hospital stay or nursing-facility care, LIFE covers that too.\n\nTo qualify, your loved one must be 55 or older, be certified by the state as needing a nursing-facility level of care, live in the service area of a LIFE provider, and be able to live safely in the community with LIFE's help when they enroll. Most participants qualify through Medicaid and pay nothing; people who are not eligible for Medicaid can still enroll and pay privately.",
      "savingsRange": "$15,000 – $35,000/year",
      "savingsSource": "Estimated value of the comprehensive medical and long-term care covered for dual-eligible participants at no cost",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 55 or older",
          "Certified as needing a nursing-facility level of care",
          "Lives in a LIFE provider's service area",
          "Able to live safely at home with LIFE services when enrolling",
          "Most participants qualify through Medicaid (Medicare-only and private-pay also accepted)"
        ],
        "ageRequirement": "55+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": "Must be clinically certified as needing a nursing-facility level of care while still being able to live safely in the community with LIFE services.",
        "otherRequirements": [
          "Must live in the service area of a participating LIFE provider"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Contact a LIFE provider that serves your loved one's county, or the PA Department of Aging, to start an enrollment assessment.",
        "steps": [
          {
            "step": 1,
            "title": "Find a LIFE provider near you",
            "description": "LIFE is delivered by local provider organizations. Contact the PA Department of Aging or your local Area Agency on Aging to find the LIFE provider that serves your loved one's county."
          },
          {
            "step": 2,
            "title": "Request an enrollment assessment",
            "description": "The provider arranges an assessment to confirm your loved one is 55+, needs a nursing-facility level of care, and can live safely at home with LIFE's support."
          },
          {
            "step": 3,
            "title": "Complete financial eligibility",
            "description": "If your loved one isn't already on Medicaid, the provider helps apply. Dual-eligible participants typically pay nothing; Medicare-only and private-pay options are available."
          },
          {
            "step": 4,
            "title": "Enroll and build a care plan",
            "description": "Once eligibility is confirmed, your loved one enrolls and the LIFE team builds an individualized care plan around the local LIFE center."
          }
        ],
        "processingTime": "Varies by provider; assessments are typically scheduled within a few weeks.",
        "waitlist": null,
        "tip": "Enrollment is voluntary and can be ended at any time. Because LIFE coordinates all care, your loved one generally uses the LIFE provider's network of doctors and specialists.",
        "urls": []
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "PA Department of Aging",
          "phone": "717-783-1550",
          "description": "Help finding the LIFE provider that serves your county",
          "hours": "Monday–Friday, business hours"
        }
      ],
      "applicationNotes": [
        "LIFE is the same model as PACE nationally; in Pennsylvania the program is branded 'LIFE.' It is separate from Pennsylvania's PACE prescription-assistance program, which only helps with drug costs.",
        "Dual-eligible participants (Medicare and Medicaid) pay no monthly premium, deductible, or copay for covered care.",
        "Because one organization coordinates all care, your loved one generally must use the LIFE provider's network of doctors and specialists."
      ],
      "relatedPrograms": [
        "Community HealthChoices (CHC)",
        "Caregiver Support Program"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Is LIFE the same as the PACE prescription program?",
          "answer": "No. Pennsylvania uses two confusingly similar names. LIFE (Living Independence for the Elderly) is the all-inclusive medical and long-term care program described here — Pennsylvania's version of the national PACE model. The other 'PACE' (Pharmaceutical Assistance Contract for the Elderly) only helps pay for prescription drugs. Your loved one can look into both."
        },
        {
          "question": "Does my loved one have to move into a nursing home to qualify?",
          "answer": "No — it's the opposite. To enroll, your loved one must be certified as needing a nursing-facility level of care but still be able to live safely at home with LIFE's support. The point of LIFE is to provide that level of care at home and at a local LIFE center so they can avoid moving into a facility."
        },
        {
          "question": "How much does LIFE cost?",
          "answer": "Most participants are eligible for both Medicare and Medicaid and pay nothing — no premium, deductible, or copay for covered services. If your loved one has Medicare but not Medicaid, they can still enroll by paying the Medicaid portion privately, and people with neither can pay the full cost out of pocket."
        },
        {
          "question": "Can my loved one keep their own doctor?",
          "answer": "Generally no. Because a single LIFE organization coordinates and pays for all care, your loved one uses that provider's team and network. If keeping a specific doctor matters, ask the LIFE provider whether that doctor is in their network before enrolling."
        }
      ],
      "layoutIntent": null,
      "icon": null,
      "phone": "717-783-1550",
      "sourceUrl": "https://www.pa.gov/agencies/aging/aging-programs-and-services.html",
      "contentStatus": "pipeline-draft",
      "draftedAt": "2026-06-19"
    },
    {
      "id": "pace-prescription-assistance",
      "name": "PACE (Pharmaceutical Assistance Contract for the Elderly) in Pennsylvania",
      "shortName": "PA PACE",
      "tagline": "Low-cost prescriptions for Pennsylvania seniors 65+ with limited income",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Statewide via Department of Aging; local PA MEDI sites",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 65+ and living on a fixed income in Pennsylvania, PACE can dramatically reduce their prescription costs. The program covers both generic and brand-name medications with co-pays of just $6 for generics and $9 for brand names, no monthly premium required.\n\nTo qualify, your loved one's previous year income must be $14,500 or less for a single person, or $17,700 for a married couple. The program has no asset limits, so your loved one's savings, home value, or investments won't disqualify them. However, they cannot be enrolled in Medicaid prescription benefits.\n\nImportant: This is Pennsylvania's prescription assistance program, not the national PACE long-term care program. If your loved one needs comprehensive medical and long-term care services (such as in-home care, therapies, and coordinated medical care), that is Pennsylvania's LIFE program, which is a separate benefit.",
      "savingsRange": "$1,200 – $3,600/year in 2026",
      "savingsSource": "Based on $6-$9 co-pays versus average prescription costs",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Age 65+",
          "Income below $14,500 (single) or $17,700 (couple)",
          "Pennsylvania resident 90+ days",
          "Not on Medicaid prescription benefits"
        ],
        "ageRequirement": "65+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Pennsylvania resident for at least 90 consecutive days",
          "Cannot be enrolled in Medicaid prescription benefits"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Apply by calling the PACE hotline at 1-800-225-7223, processing time not specified.",
        "steps": [
          {
            "step": 1,
            "title": "Gather income documents",
            "description": "Collect proof of previous year's income including Social Security statements, tax returns, and 1099s for pensions or wages."
          },
          {
            "step": 2,
            "title": "Call the PACE hotline",
            "description": "Call 1-800-225-7223 to start your application. You can also call the PA MEDI helpline at 1-800-783-7067 for application assistance."
          },
          {
            "step": 3,
            "title": "Complete application online",
            "description": "Visit pacecares.magellanhealth.com to complete your application with income verification and residency documentation."
          },
          {
            "step": 4,
            "title": "Submit required documents",
            "description": "Provide proof of age, Pennsylvania residency for 90+ days, and verification that you're not enrolled in Medicaid prescription benefits."
          }
        ],
        "processingTime": "Not specified",
        "waitlist": null,
        "tip": "Income is based on the previous calendar year, so if your loved one's income dropped recently, they may still need to wait until next year to qualify.",
        "urls": [
          {
            "label": "PACE Application Portal",
            "url": "https://pacecares.magellanhealth.com/"
          },
          {
            "label": "PA Department of Aging PACE Program",
            "url": "https://www.pa.gov/agencies/aging/aging-programs-and-services/pace-program"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security award letter or statement from previous year",
        "Previous year's tax return (1040 or 1040EZ)",
        "1099 forms for pension income",
        "1099 forms for any wage income",
        "Proof of Pennsylvania residency for 90+ consecutive days (utility bills, lease agreement, or state-issued document)",
        "Birth certificate or other proof of age 65+",
        "Medicare card showing you're not enrolled in Medicaid prescription benefits",
        "Documentation of any other income sources from previous calendar year",
        "Bank statements if you received interest income over $10"
      ],
      "contacts": [
        {
          "label": "PACE Hotline",
          "phone": "1-800-225-7223",
          "description": "Primary application and program information line",
          "hours": "Business hours"
        },
        {
          "label": "PA MEDI Helpline",
          "phone": "1-800-783-7067",
          "description": "Local assistance with PACE applications",
          "hours": "Business hours"
        },
        {
          "label": "PA Department of Aging",
          "phone": "717-783-1550",
          "description": "General aging services and program information",
          "hours": "Mon-Fri 8am-5pm"
        }
      ],
      "applicationNotes": [
        "If your loved one sold their home, all capital gains must be declared as income within two years of the sale date. However, if they sold their home to pay for nursing home costs or used the proceeds to purchase another primary residence, those proceeds are typically not considered income.",
        "Medicare Part B premiums are excluded from your income calculation.",
        "If your loved one is already enrolled in the full Medicaid prescription benefit, they are not eligible for PACE/PACENET.",
        "While income limits do not automatically adjust for inflation, the Pennsylvania General Assembly periodically passes legislation to update eligibility thresholds and implement moratoriums to protect seniors from losing eligibility solely due to Social Security cost-of-living adjustments (COLAs).",
        "Eligibility is based on the previous calendar year's gross income. If your loved one's income varies, they will indeed be re-evaluated annually based on that previous year's earnings. Because income is based on the prior year, a recent drop in income will not result in immediate eligibility; they will need to wait until the next annual evaluation cycle to report their lower income."
      ],
      "relatedPrograms": [
        "PACENET (higher income prescription assistance)",
        "Medicare Part D",
        "Pennsylvania LIHEAP",
        "Property Tax/Rent Rebate Program"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my loved one apply if they own their home outright?",
          "answer": "Yes. PACE has no asset limits, so home ownership, savings accounts, or investments won't disqualify your loved one. Only income from the previous calendar year matters for eligibility."
        },
        {
          "question": "What if my loved one is on Medicare Part D, can they still get PACE?",
          "answer": "Yes, your loved one can have Medicare Part D and PACE at the same time. However, they cannot be enrolled in Medicaid prescription benefits (Medical Assistance pharmaceutical benefits)."
        },
        {
          "question": "My loved one's income was higher last year but dropped this year, when can they apply?",
          "answer": "PACE eligibility is primarily based on the previous calendar year's gross income. However, if your loved one has experienced a significant, permanent change in income, the PACE program may offer a 'financial change of status' review. Instead of waiting until the next calendar year, call the PACE hotline at 1-800-225-7223 to explain the situation; they can determine if your loved one qualifies for a re-evaluation based on their current circumstances."
        },
        {
          "question": "Does Social Security count toward the income limit?",
          "answer": "Yes, gross Social Security income counts, but Medicare premiums deducted from Social Security are excluded. The program looks at Social Security before Medicare Part B premiums are taken out."
        },
        {
          "question": "Can I apply for my loved one if they can't manage the application themselves?",
          "answer": "The application process allows for assistance, but you'll need to call the PACE hotline at 1-800-225-7223 to discuss representing your loved one and what documentation may be required."
        },
        {
          "question": "What happens if my loved one needs a prescription that's not covered?",
          "answer": "PACE covers a wide range of medications through its comprehensive formulary. If your loved one takes a specific drug, you can check the online formulary on the PACE website to see if it is covered before applying. If a medication is not on the list, there is a formal exception process that your loved one's doctor can initiate on their behalf."
        },
        {
          "question": "If my loved one moves to another state, can they keep PACE benefits?",
          "answer": "No. PACE requires Pennsylvania residency for at least 90 consecutive days before application and continued residency to maintain benefits. Moving out of state ends eligibility."
        },
        {
          "question": "How long do PACE benefits last once approved?",
          "answer": "The program materials don't specify renewal requirements or benefit duration. Call 1-800-225-7223 to ask about renewal processes and how long benefits continue."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "savings",
        "eligibilityDisplay": "income-table",
        "applyDisplay": "step-journey",
        "hasLocationFinder": false,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "Pill",
      "phone": "1-800-225-7223",
      "sourceUrl": "https://www.pa.gov/agencies/aging/aging-programs-and-services/pace-program",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "healthy-horizons-qmb-slmb-qi",
      "name": "Healthy Horizons (QMB, SLMB, QI)",
      "shortName": "Healthy Horizons",
      "tagline": "Save on Medicare costs: See if your loved one qualifies for Pennsylvania’s Healthy Horizons.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local CAO in each PA county",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 65+ with Medicare and struggling with out-of-pocket medical costs, Pennsylvania's Healthy Horizons program can help. This program offers different levels of assistance depending on income: the QMB tier can cover Medicare Part A and B premiums, deductibles, and coinsurance, while SLMB and QI tiers provide assistance with the Medicare Part B premium.\n\nTo qualify, your loved one must be entitled to Medicare Part A and meet income and resource limits. Because these calculations can include spousal income and assets, the financial picture may be complex, but the potential savings are significant for those who qualify.",
      "savingsRange": "$200 – $3,000/year in 2026",
      "savingsSource": "Medicare Part B premium ($185/month in 2026) plus deductibles and copayments",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 65+ or disabled",
          "Entitled to Medicare Part A",
          "Income up to $1,350–$2,279/month (varies by tier)",
          "Assets up to $2,000–$14,910 (varies by tier)",
          "Pennsylvania resident"
        ],
        "ageRequirement": "65+",
        "incomeTable": [
          {
            "householdSize": 1,
            "monthlyLimit": 1350
          },
          {
            "householdSize": 2,
            "monthlyLimit": 1824
          }
        ],
        "assetLimits": {
          "individual": 9950,
          "couple": 14910,
          "countedAssets": [
            "Bank accounts",
            "Stocks",
            "Second car",
            "Investment accounts"
          ],
          "exemptAssets": [
            "Primary home",
            "One car",
            "Personal belongings",
            "Burial plots",
            "Life insurance up to $1,500 face value"
          ],
          "homeEquityCap": null
        },
        "functionalRequirement": null,
        "otherRequirements": [
          "Must be entitled to Medicare Part A (even if not enrolled)",
          "Pennsylvania resident",
          "U.S. citizen or qualified immigrant",
          "Spouse income and resources counted if married"
        ],
        "povertyLevelReference": "100-175% FPL"
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Apply online through COMPASS, by phone through your County Assistance Office, or in person, processing takes up to 45 days.",
        "processingTime": "Up to 45 days; effective first of month after all info received (QMB); SLMB/QI retroactive up to 3 months",
        "waitlist": null,
        "steps": [
          {
            "step": 1,
            "title": "Find your County Assistance Office",
            "description": "Call 1-866-550-4355 to find your local CAO or use the DHS office locator at pa.gov. Each of Pennsylvania's 67 counties has a CAO that processes applications."
          },
          {
            "step": 2,
            "title": "Apply online or by phone",
            "description": "Apply online at COMPASS by selecting \"Medical Assistance.\" Alternatively, you can request a PA 600M form to complete by mail or call your local CAO directly to start an application over the phone."
          },
          {
            "step": 3,
            "title": "Submit required documents",
            "description": "Provide proof of income, resources, Medicare entitlement, and residency. Missing documents are the most common cause of delays."
          },
          {
            "step": 4,
            "title": "Wait for processing",
            "description": "Your CAO will screen for all tiers automatically, if you don't qualify for QMB, they'll check SLMB and QI eligibility. You'll receive a decision within 45 days."
          }
        ],
        "tip": "Submit all documents at once, incomplete applications cause most delays. Your CAO must screen for all program tiers, so you don't need to specify which one you want.",
        "urls": [
          {
            "label": "COMPASS Online Application",
            "url": "https://www.compass.state.pa.us"
          },
          {
            "label": "PA DHS Office Locator",
            "url": "https://www.pa.gov/agencies/dhs/"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security award letter or disability determination",
        "Medicare card or proof of Part A entitlement",
        "Pay stubs for last 3 months (if working)",
        "Pension or retirement income statements",
        "Bank statements for all accounts (last 3 months)",
        "Investment account statements (stocks, bonds, annuities)",
        "Birth certificate or other proof of age",
        "Social Security card",
        "Proof of Pennsylvania residency (utility bill, lease)",
        "Vehicle titles and registration",
        "Life insurance policies showing face value",
        "Property deeds or tax statements",
        "Burial plot deeds or pre-need burial contracts",
        "Spouse's income and asset documentation (if married)",
        "Unpaid medical bills (for retroactive coverage requests)"
      ],
      "contacts": [
        {
          "label": "County Assistance Office Locator",
          "phone": "(866) 550-4355",
          "description": "Find your local CAO for application help",
          "hours": "Business hours vary by county"
        },
        {
          "label": "PA Department of Human Services",
          "phone": "(800) 692-7462",
          "description": "General Medicaid and benefits information",
          "hours": "Mon-Fri 8am-5pm ET"
        }
      ],
      "applicationNotes": [
        "Automatic Screening: Your County Assistance Office (CAO) will screen you for all tiers of Healthy Horizons. If you do not qualify for QMB, they will automatically check your eligibility for SLMB and QI.",
        "Spousal Income & Assets: If you are married, your spouse's income and resources are included in the calculation, even if they are not applying themselves. This is a common factor that can impact eligibility.",
        "QI Exclusivity: If you qualify for the QI program, you cannot receive full-scope Medicaid coverage at the same time. QI only provides assistance with your Medicare Part B premium.",
        "Asset Rules: While the resource limits are more generous for Medicare Savings Programs ($9,950 for individuals), the rules remain strict. Items like a second vehicle, investment accounts, or real estate that is not your primary residence are counted toward your total assets."
      ],
      "relatedPrograms": [
        "Pennsylvania Medicaid",
        "SNAP (Food Assistance)",
        "LIHEAP (Energy Assistance)",
        "Medicare Extra Help (Low Income Subsidy)"
      ],
      "contentSections": [
        {
          "type": "tier-comparison",
          "title": "Program Tiers and Benefits",
          "content": "**QMB Categorically Needy:** Full Medicaid plus all Medicare Part A/B premiums, deductibles, and copayments covered. Income limit: $1,350/month individual, $1,824 couple. Assets: $2,000 individual, $3,000 couple.\n\n**QMB Cost-Sharing Only:** Medicare Part A/B premiums, deductibles, and copayments covered (no other Medicaid benefits). Higher asset limits: $9,950 individual, $14,910 couple.\n\n**SLMB:** Medicare Part B premium only ($185/month in 2026). Income up to 120% FPL. Assets: $9,950 individual, $14,910 couple.\n\n**QI-1 and QI-2:** Medicare Part B premium only. QI-1 up to 135% FPL, QI-2 up to 175% FPL. Same asset limits as SLMB. Cannot have full Medicaid."
        }
      ],
      "faqs": [
        {
          "question": "Can my loved one keep their house if it's worth more than the asset limit?",
          "answer": "Yes, the primary home is exempt from asset limits regardless of value, provided the applicant lives there. Only countable assets like bank accounts, stocks, and secondary vehicles count toward the current 2026 resource limits of $9,950 for an individual or $14,910 for a married couple."
        },
        {
          "question": "What happens if my loved one's income is too high for QMB but might qualify for SLMB?",
          "answer": "The County Assistance Office automatically screens for all tiers. If your loved one doesn't qualify for QMB (full benefits), they'll check SLMB and QI eligibility without you needing to file a separate application."
        },
        {
          "question": "Does my loved one's spouse's income count even if the spouse isn't applying?",
          "answer": "Yes, spouse income and resources are always counted in the eligibility calculation. This is a common source of confusion and application denials. You must provide documentation for both spouses' finances."
        },
        {
          "question": "Can my loved one get retroactive coverage for medical bills they already paid?",
          "answer": "SLMB and QI can be retroactive up to 3 months, but QMB cost-sharing benefits (premiums and deductibles) cannot be applied retroactively. Bring unpaid medical bills to your CAO when applying."
        },
        {
          "question": "How much will this actually save on Medicare costs?",
          "answer": "At a minimum, Medicare Part B premium coverage saves $202.90 per month ($2,434.80 per year in 2026). Full QMB coverage adds significant protection by covering the Medicare Part A inpatient hospital deductible ($1,736 per benefit period), the annual Part B deductible ($283), and 20% coinsurance for doctor visits and outpatient services. For someone with regular medical needs, this can mean thousands of dollars in annual savings."
        },
        {
          "question": "Can I apply for my loved one if they have dementia or can't handle paperwork?",
          "answer": "Yes, family members can apply on behalf of elderly loved ones. You'll need to provide legal documentation if you're the appointed representative, or the CAO can help determine what authorization is needed."
        },
        {
          "question": "What if my loved one already has Medicare Supplement insurance?",
          "answer": "Healthy Horizons can work alongside Medicare Supplement plans, but the benefits may overlap. Your loved one might be able to drop expensive supplement coverage and save money while getting similar or better coverage through the state program."
        },
        {
          "question": "How long does coverage last once approved?",
          "answer": "Coverage continues as long as your loved one meets eligibility requirements. The state will review eligibility periodically (usually annually), and you'll need to report changes in income or resources that might affect benefits."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "savings",
        "eligibilityDisplay": "income-table",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "ShieldCheck",
      "phone": "(866) 550-4355",
      "sourceUrl": "https://www.pa.gov/agencies/dhs/resources/aging-physical-disabilities/medicaid-older-people-and-people-with-disabilities",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "snap-food-benefits",
      "name": "SNAP (Supplemental Nutrition Assistance Program)",
      "shortName": "SNAP Food Benefits",
      "tagline": "Monthly food support to help seniors stay healthy and independent at home.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "federal",
        "stateVariation": true,
        "localEntities": [
          {
            "name": "Local County Assistance Offices",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 60 or older and struggling to afford groceries, SNAP can help. Benefits are loaded onto an EBT card each month, which works like a debit card at most grocery stores, farmers' markets, and authorized online retailers like Amazon and Walmart.  <br>The amount your loved one receives is based on their unique financial situation—including their household size, income, and allowable expenses like housing and out-of-pocket medical costs. While the maximum benefit for a single person in the 48 contiguous states is **$298 per month** (and **$546** for a two-person household), many households receive an amount tailored to their specific needs.  <br>Pennsylvania makes it easier for seniors to qualify than younger adults. Even if your loved one's gross income is slightly above the standard limit, they may still qualify by using special 'net income' rules that account for high medical and housing expenses. Furthermore, Pennsylvania does not have an asset test for most SNAP applicants, meaning your loved one can typically maintain eligibility while owning their home, a car, and modest savings.",
      "savingsRange": "$100 – $3,276/year in 2026",
      "savingsSource": "Average $106/month for older adults, maximum $273/month for individuals",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "Income below $2,608/month (single)",
          "U.S. citizen or qualified immigrant",
          "Lives in Pennsylvania"
        ],
        "ageRequirement": "60+",
        "incomeTable": [
          {
            "householdSize": 1,
            "monthlyLimit": 2608
          },
          {
            "householdSize": 2,
            "monthlyLimit": 3526
          },
          {
            "householdSize": 3,
            "monthlyLimit": 4442
          },
          {
            "householdSize": 4,
            "monthlyLimit": 5358
          },
          {
            "householdSize": 5,
            "monthlyLimit": 6276
          },
          {
            "householdSize": 6,
            "monthlyLimit": 7192
          }
        ],
        "assetLimits": {
          "individual": 4500,
          "couple": 4500,
          "countedAssets": [
            "Bank accounts over $4,500",
            "Investment accounts",
            "Extra vehicles worth over $4,650"
          ],
          "exemptAssets": [
            "Primary home",
            "One vehicle",
            "Income-producing vehicles",
            "Burial funds"
          ],
          "homeEquityCap": null
        },
        "functionalRequirement": null,
        "otherRequirements": [
          "Must buy and prepare food together with others counted in household",
          "Medical expenses and housing costs are deducted to increase benefits"
        ],
        "povertyLevelReference": "200% FPL"
      },
      "applicationGuide": {
        "method": "multiple",
        "summary": "Apply online through Pennsylvania's COMPASS website or call your County Assistance Office, processing time varies by county.",
        "steps": [
          {
            "step": 1,
            "title": "Check if you qualify",
            "description": "Use the 'Do I Qualify?' tool on the COMPASS website (www.compass.state.pa.us) to get an instant eligibility estimate."
          },
          {
            "step": 2,
            "title": "Gather required documents",
            "description": "Collect Social Security numbers, income statements, and housing/medical expense records for everyone who buys and prepares food together."
          },
          {
            "step": 3,
            "title": "Submit application",
            "description": "Apply online at www.compass.state.pa.us, call your local County Assistance Office, or request the Simple SNAP application by phone if everyone in the household is 60+ or disabled."
          },
          {
            "step": 4,
            "title": "Complete interview",
            "description": "Your County Assistance Office will schedule a phone or in-person interview to review your application and verify information."
          },
          {
            "step": 5,
            "title": "Receive decision",
            "description": "You'll get a written decision by mail. If approved, your EBT card arrives within 10 days and benefits typically start the month after approval."
          }
        ],
        "processingTime": "Varies by county; expedited processing available for urgent financial need",
        "waitlist": null,
        "tip": "Seniors over the gross income limit can still qualify through net income rules, don't assume you make too much without applying.",
        "urls": [
          {
            "label": "COMPASS Application Portal",
            "url": "https://www.compass.state.pa.us"
          },
          {
            "label": "Pennsylvania SNAP for Older Adults",
            "url": "https://www.pa.gov/agencies/dhs/resources/snap/snap-older-adults"
          }
        ]
      },
      "documentsNeeded": [
        "Social Security numbers for all household members",
        "Dates of birth for all household members",
        "Social Security award letters or benefit statements",
        "Pension or retirement income statements",
        "Bank statements for all accounts (last 3 months)",
        "Current rent receipt or mortgage statement",
        "Utility bills (electric, gas, water, phone)",
        "Medical expense receipts and bills (last 3 months)",
        "Health insurance premium statements",
        "Prescription drug cost documentation",
        "Property tax bills or homeowner's insurance",
        "Vehicle registration or title",
        "Immigration documents (if applicable)"
      ],
      "contacts": [
        {
          "label": "Central PA Food Bank SNAP Hotline",
          "phone": "(877) 999-5964",
          "description": "SNAP application assistance and questions",
          "hours": "Monday-Friday, business hours"
        },
        {
          "label": "PA Department of Human Services",
          "phone": "2-1-1",
          "description": "Find your local County Assistance Office and get general benefit information",
          "hours": "24 hours, 7 days a week"
        },
        {
          "label": "COMPASS Helpline",
          "phone": "(800) 692-7462",
          "description": "Technical help with online applications",
          "hours": "Monday-Friday 8am-5pm"
        },
        {
          "label": "PA Department of Human Services Statewide Customer Service Center",
          "phone": "(877) 395-8930",
          "description": "For questions about an active case, to report income changes, or to speak directly with a caseworker",
          "hours": "Monday–Friday, business hours"
        }
      ],
      "applicationNotes": [
        "If all members of your household are 60 or older or receive SSI/SSDI and have no earned income, you may qualify for the Elderly Simplified Application Project (ESAP). This process is designed to reduce paperwork and simplify your renewal.",
        "If your household is facing immediate food insecurity and meets specific low-income criteria, you may qualify for 'expedited processing,' which requires the state to provide benefits within 5 calendar days. Be sure to mention your emergency situation immediately when you apply.",
        "Medical expenses over $35/month are deducted from income to increase benefit amounts, save all receipts",
        "Starting February 2026, you must verify shelter and utility costs when applying, renewing benefits, or moving to a new address"
      ],
      "relatedPrograms": [
        "LIHEAP (Low Income Home Energy Assistance)",
        "Pennsylvania Property Tax/Rent Rebate Program",
        "Medicaid",
        "Medicare Extra Help (Part D)"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my loved one keep their house and still get SNAP benefits?",
          "answer": "Yes. Your loved one's primary home doesn't count toward asset limits, regardless of value. They can also keep one vehicle and reasonable personal belongings without affecting SNAP eligibility."
        },
        {
          "question": "What if my loved one's income is slightly over the limit but they have high medical bills?",
          "answer": "Even if your loved one's gross income is above the standard limit, they may still qualify. Seniors (60+) can deduct verified out-of-pocket medical expenses that exceed $35/month from their income. These deductions lower their countable income, often bringing them under the limit to qualify for benefits. Always apply; many seniors are surprised to find they are eligible after these deductions are applied."
        },
        {
          "question": "Can I apply for SNAP on behalf of my elderly loved one?",
          "answer": "Yes, adult children can apply as authorized representatives if their loved one gives permission. You'll need to complete an authorized representative form and may need to attend the eligibility interview with or instead of your loved one."
        },
        {
          "question": "How much will my loved one actually receive each month?",
          "answer": "It depends on net income after deductions. For example, a single senior with $1,500/month income and $200 in medical expenses might receive around $150/month. Use the COMPASS calculator for a personalized estimate before applying."
        },
        {
          "question": "Can my loved one use SNAP benefits to buy groceries online?",
          "answer": "Yes. Pennsylvania SNAP recipients can use their EBT card for online grocery orders from Amazon, Walmart, and other approved retailers. Delivery fees aren't covered by SNAP, but the groceries are."
        },
        {
          "question": "What happens if my loved one lives with family but buys their own food?",
          "answer": "Only people who buy and prepare food together count as one SNAP household. If your loved one shops and cooks separately, they apply as a one-person household even if they live with relatives."
        },
        {
          "question": "How often does my loved one need to renew SNAP benefits?",
          "answer": "Seniors often receive a longer certification period—typically 24 or 36 months—making it easier to maintain benefits without frequent paperwork. You will receive renewal notices in the mail with clear instructions on when to recertify. Keep an eye on your mail, as missing these notices can cause a gap in coverage."
        },
        {
          "question": "Can my loved one get SNAP if they're already receiving Medicaid or Medicare?",
          "answer": "Yes. SNAP is a separate program from health insurance. Many seniors receive SNAP, Medicaid, Medicare, and other benefits simultaneously. Being on one program doesn't disqualify you from others."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "savings",
        "eligibilityDisplay": "income-table",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "BowlFood",
      "phone": "(877) 999-5964",
      "sourceUrl": "https://www.pa.gov/agencies/dhs/resources/snap/snap-older-adults",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "ship-medicare-counseling",
      "name": "SHIP (State Health Insurance Assistance Program)",
      "shortName": "SHIP Medicare Help",
      "tagline": "Free one-on-one counseling to help your loved one navigate Medicare options and find cost savings.",
      "programType": "resource",
      "complexity": "simple",
      "geographicScope": {
        "type": "federal",
        "stateVariation": true,
        "localEntities": [
          {
            "name": "PA MEDI – Pennsylvania Medicare Education and Decision Insight (statewide contact); local sites via shiphelp.org",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one has Medicare and feels overwhelmed by plan choices, prescription costs, or billing errors, Pennsylvania's SHIP program provides free expert guidance. SHIP counselors help Medicare beneficiaries understand their options for Original Medicare, Medicare Advantage, Medicare Supplement plans, and prescription drug coverage, plus identify potential savings through programs like Medicare Savings Programs and Extra Help.\n\nBecause SHIP counselors are trained, certified, and independent (not insurance salespeople), your loved one gets unbiased advice tailored to their specific health needs and budget. The program also includes fraud protection services to help spot billing errors that could cost hundreds or thousands of dollars. No income limits apply, any Pennsylvania Medicare beneficiary can get help, though priority goes to those with limited incomes or disabilities.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Medicare beneficiary",
          "Pennsylvania resident",
          "No income limits",
          "Priority for limited incomes"
        ],
        "ageRequirement": null,
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Must be a Medicare beneficiary (or family/caregiver of one)",
          "Must be a Pennsylvania resident"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call the PA MEDI helpline, counselors provide immediate guidance and can schedule deeper consultations.",
        "steps": [
          {
            "step": 1,
            "title": "Call PA MEDI",
            "description": "Call 1-800-783-7067 to reach Pennsylvania's Medicare counseling helpline. Counselors are available during business hours."
          },
          {
            "step": 2,
            "title": "Describe your needs",
            "description": "Tell the counselor what Medicare questions you have, plan comparisons, prescription costs, billing problems, or help applying for cost assistance programs."
          },
          {
            "step": 3,
            "title": "Get personalized guidance",
            "description": "The counselor will provide immediate answers and may schedule a longer consultation or connect you with a local counselor near you."
          }
        ],
        "processingTime": "Immediate phone assistance, no formal application or processing time",
        "waitlist": null,
        "tip": "Have your loved one's Medicare card and current plan information handy when you call, this helps counselors give more specific advice.",
        "urls": [
          {
            "label": "PA SHIP Information",
            "url": "https://www.shiphelp.org/ships/pennsylvania/"
          }
        ]
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "PA MEDI Medicare Counseling",
          "phone": "1-800-783-7067",
          "description": "Free Medicare counseling and assistance for Pennsylvania residents",
          "hours": "Business hours (contact for specific schedule)"
        },
        {
          "label": "National SHIP Locator",
          "phone": "1-877-839-2675",
          "description": "Find local SHIP counselors nationwide",
          "hours": "Business hours"
        }
      ],
      "applicationNotes": null,
      "relatedPrograms": [
        "Medicare Savings Programs",
        "Extra Help (Low Income Subsidy)",
        "Medicaid"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can I call SHIP on behalf of my loved one who has Medicare?",
          "answer": "Yes, family caregivers can contact SHIP for guidance about their loved one's Medicare options. Counselors can explain plan choices and programs to you, though they may need to speak directly with your loved one for certain personal information or to help with applications."
        },
        {
          "question": "How is SHIP different from insurance agents who say they help with Medicare?",
          "answer": "SHIP counselors are trained and certified but don't sell insurance, they provide unbiased guidance about all available options. Insurance agents typically represent specific companies and earn commissions from sales, while SHIP counselors work for you and your loved one's best interests."
        },
        {
          "question": "Can SHIP help if my loved one thinks Medicare billed them incorrectly?",
          "answer": "Yes, SHIP includes Senior Medicare Patrol services specifically to help detect and report Medicare fraud, errors, and abuse. Counselors can help your loved one understand their Medicare statements and take action if they spot billing problems."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "phone-cta",
        "hasLocationFinder": true,
        "hasDocumentChecklist": false,
        "visualTone": "minimal"
      },
      "icon": "Compass",
      "phone": "1-800-783-7067",
      "sourceUrl": "https://www.shiphelp.org/ships/pennsylvania/",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "home-delivered-meals",
      "name": "Home-Delivered Meals (Meals on Wheels)",
      "shortName": "Meals on Wheels",
      "tagline": "Healthy Meals at Home: Support for Your Loved One's Daily Independence.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "federal",
        "stateVariation": true,
        "localEntities": [
          {
            "name": "York County AAA",
            "type": "service-area"
          },
          {
            "name": "Blair Senior Services",
            "type": "service-area"
          },
          {
            "name": "Armstrong County AAA",
            "type": "service-area"
          },
          {
            "name": "Montgomery County",
            "type": "service-area"
          },
          {
            "name": "Philadelphia Corporation for Aging (PCA)",
            "type": "service-area"
          },
          {
            "name": "Local AAAs statewide via PA Department of Aging",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 60 or older and struggles to shop for groceries or prepare meals safely due to physical, mental, or emotional limitations, they may qualify for home-delivered meal programs. These services are coordinated through Pennsylvania's local Area Agencies on Aging (AAAs). When you apply, a care manager will conduct an assessment to confirm eligibility, which includes verifying that your loved one is homebound and lacks the support to prepare adequate meals.\n\nPlease keep in mind that these programs are not universally free or guaranteed to be delivered five days a week in every location. Delivery frequency and meal types vary significantly by county, and many programs are publicly funded and may request a voluntary donation. Due to high demand, some counties may also have waiting lists. Since Pennsylvania has 52 different Area Agencies on Aging, service availability depends on where your loved one lives. The best first step is to contact your local Area Agency on Aging to request an assessment and find out what is specifically available in your community.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "Pennsylvania resident",
          "Homebound or unable to cook safely",
          "Living alone or with someone who also qualifies",
          "Requires in-home assessment"
        ],
        "ageRequirement": "60+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": "Must have physical, mental, or emotional disability preventing leaving home regularly and/or preparing nutritious meals safely",
        "otherRequirements": [
          "Pennsylvania resident in non-institutional home setting",
          "Cannot have family or informal supports available for meals and shopping",
          "Must live alone or with someone who also qualifies"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call your local Area Agency on Aging for an in-home assessment, processing time varies by county.",
        "steps": [
          {
            "step": 1,
            "title": "Find your local Area Agency on Aging",
            "description": "Pennsylvania has 52 Area Agencies covering all 67 counties. Examples: York County 717-771-9610, Blair County 814-946-1235, or search the PA Department of Aging website."
          },
          {
            "step": 2,
            "title": "Call for intake interview",
            "description": "Explain your loved one's situation regarding meal preparation, shopping ability, and available family support. Be prepared to discuss their living situation and functional limitations."
          },
          {
            "step": 3,
            "title": "Schedule in-home assessment",
            "description": "A care manager will visit your loved one's home to evaluate their ability to prepare meals and leave home safely. This assessment is required for all applicants."
          },
          {
            "step": 4,
            "title": "Await approval and service start",
            "description": "If approved, your local provider will contact your loved one to arrange meal delivery schedule, dietary accommodations, and delivery instructions."
          }
        ],
        "processingTime": "Not specified; requires in-home assessment prior to service start",
        "waitlist": null,
        "tip": "Have information ready about your loved one's medical conditions, current diet restrictions, and what family help is available for shopping or cooking.",
        "urls": [
          {
            "label": "PA Department of Aging Meals Program",
            "url": "https://www.pa.gov/agencies/aging/aging-programs-and-services/meals-and-food-assistance"
          }
        ]
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "York County Area Agency on Aging",
          "phone": "(717) 771-9610",
          "description": "Intake and assessment for York County residents",
          "hours": "Contact for hours"
        },
        {
          "label": "Blair Senior Services",
          "phone": "(814) 946-1235",
          "description": "Home-delivered meals for Blair County",
          "hours": "Contact for hours"
        },
        {
          "label": "PA Department of Aging",
          "phone": "Contact local AAA",
          "description": "Statewide program information and local office referrals",
          "hours": "Varies by county"
        }
      ],
      "applicationNotes": [
        "You cannot self-qualify, every applicant needs an in-home assessment by local Area Agency on Aging staff",
        "Some counties emphasize financial need while others focus purely on functional limitations, ask about specific requirements in your area",
        "This program is separate from Medicaid waiver meals, which have stricter financial requirements and nursing home-level care needs",
        "If your loved one has family available to help with shopping or cooking, they likely won't qualify"
      ],
      "relatedPrograms": [
        "SNAP (Food Stamps)",
        "Senior Farmers Market Nutrition Program",
        "Senior Food Box Program",
        "Congregate Meal Sites"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can my loved one get meals if they have family nearby who could help?",
          "answer": "Likely not. The program excludes people who have family or informal supports available for meals and shopping. The assessment will evaluate what help your loved one actually receives, not just what's theoretically available."
        },
        {
          "question": "What if my loved one can still drive but just doesn't cook much anymore?",
          "answer": "They need to demonstrate they cannot prepare nutritious meals due to physical, mental, or emotional limitations, not just preference. The in-home assessment will evaluate their actual cooking ability and safety in the kitchen."
        },
        {
          "question": "How much do the meals cost?",
          "answer": "Many counties provide meals at no cost, like York County. However, some counties may require payment based on financial need. Ask your local Area Agency on Aging about costs during the intake interview."
        },
        {
          "question": "Can I apply on behalf of my loved one?",
          "answer": "You can initiate contact with the Area Agency on Aging, but your loved one will need to participate in the in-home assessment. The care manager needs to evaluate your loved one's living situation and functional abilities directly."
        },
        {
          "question": "What if my loved one lives in assisted living or senior housing?",
          "answer": "They must live in a non-institutional home setting to qualify. Assisted living typically wouldn't qualify, but senior housing apartments might depending on the level of meal services already provided."
        },
        {
          "question": "Is this the same as the Meals on Wheels I can donate to?",
          "answer": "It's the same type of service, but Pennsylvania's program is administered through 52 different Area Agencies on Aging with varying local providers. Some areas may contract with traditional Meals on Wheels organizations, others use different meal delivery companies."
        },
        {
          "question": "What happens if my loved one's condition changes after they start receiving meals?",
          "answer": "Contact your local Area Agency on Aging if your loved one's functional abilities improve significantly or if they no longer need the service. They'll reassess eligibility as needed."
        },
        {
          "question": "Can my loved one choose what meals they receive?",
          "answer": "Menus are planned by dietitians and certified by the PA Department of Aging, but they do accommodate medical conditions like diabetes and heart disease. Discuss dietary restrictions during your intake interview."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "phone-cta",
        "hasLocationFinder": true,
        "hasDocumentChecklist": false,
        "visualTone": "editorial"
      },
      "icon": "BowlFood",
      "phone": null,
      "sourceUrl": "https://www.pa.gov/agencies/aging/aging-programs-and-services/meals-and-food-assistance",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "caregiver-support-program",
      "name": "Caregiver Support Program",
      "shortName": "Caregiver Support",
      "tagline": "Get reimbursed for respite care and supplies while caring for your aging loved one in Pennsylvania.",
      "programType": "benefit",
      "complexity": "deep",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Local Area Agency on Aging (AAA) offices by county",
            "type": "service-area"
          }
        ]
      },
      "intro": "If you're caring for a loved one 60+ with functional deficits or Alzheimer's in Pennsylvania, this program reimburses you for respite care, supplies, and other caregiving expenses. The reimbursement percentage depends on your loved one's household income, up to 100% for lower incomes, scaled down to 0% above 380% of the Federal Poverty Level ($58,320 for a single person in 2026).\n\nYou pay upfront for approved services and submit receipts for reimbursement. Beyond financial help, the program provides care management, caregiver education, and training at no cost regardless of income. An in-home assessment determines what services you're authorized to receive.\n\nThe program also covers caregivers 55+ raising grandchildren or caring for disabled adult children (18-59) with different co-residence requirements. Each of Pennsylvania's 52 counties administers the program through their Area Agency on Aging, so services and wait times may vary by location.",
      "savingsRange": "",
      "savingsSource": "Reimbursement service based on sliding scale",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Caregiver and care receiver both live in Pennsylvania",
          "Care receiver 60+ with functional deficits or any age with Alzheimer's",
          "No income limits to qualify",
          "Reimbursement based on care receiver's household income"
        ],
        "ageRequirement": null,
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": "Care receiver must have functional deficits (needing help with daily activities like bathing, dressing, medication management) or Alzheimer's/related disorder diagnosis",
        "otherRequirements": [
          "Both caregiver and care receiver must reside in Pennsylvania",
          "Caregiver must be primarily responsible for providing regular care",
          "No relation or co-residence required for caring for someone 60+ or with Alzheimer's",
          "Different rules apply for caregivers 55+ raising grandchildren or caring for disabled adults 18-59"
        ],
        "povertyLevelReference": "380% FPL"
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Contact your county's Area Agency on Aging for an in-home assessment, no standard application form required.",
        "steps": [
          {
            "step": 1,
            "title": "Find your local Area Agency on Aging",
            "description": "Visit https://www.pa.gov/services/aging/apply-for-the-caregiver-support-program to find your county's AAA contact information."
          },
          {
            "step": 2,
            "title": "Call to request an assessment",
            "description": "Contact your local AAA office to schedule an in-home assessment. Each county has different phone numbers and procedures."
          },
          {
            "step": 3,
            "title": "Complete the in-home assessment",
            "description": "An assessor will evaluate your caregiving situation and determine what services you're authorized to receive."
          },
          {
            "step": 4,
            "title": "Get approval for specific services",
            "description": "Your care manager will authorize specific reimbursable services based on your assessment results."
          },
          {
            "step": 5,
            "title": "Pay for services and submit receipts",
            "description": "You pay providers upfront, then submit receipts to your care manager for reimbursement according to your income-based percentage."
          }
        ],
        "processingTime": "Requires in-home assessment; timeline varies by county",
        "waitlist": "May vary by region",
        "tip": "Gather income documentation for your care receiver before calling, this determines your reimbursement percentage.",
        "urls": [
          {
            "label": "Find Your Local Area Agency on Aging",
            "url": "https://www.pa.gov/services/aging/apply-for-the-caregiver-support-program"
          }
        ]
      },
      "documentsNeeded": [
        "Verification of care receiver's total gross household income",
        "Documentation of functional deficits or medical diagnosis for care receiver",
        "Proof of Pennsylvania residency for both caregiver and care receiver",
        "Alzheimer's or related disorder diagnosis (if applicable)",
        "Disability documentation for care receiver aged 18-59 (if applicable)",
        "Legal guardianship papers (if applicable for grandparent caregivers)",
        "Receipts for caregiving expenses to be reimbursed"
      ],
      "contacts": [
        {
          "label": "Pennsylvania Aging Services",
          "phone": "(717) 783-1550",
          "description": "General program information",
          "hours": "Mon-Fri 8am-5pm ET"
        },
        {
          "label": "Local Area Agency on Aging",
          "phone": "Varies by county",
          "description": "Your Local Area Agency on Aging (AAA)\nFor help with specific services, application forms, or to schedule an in-home assessment.\nVisit the official PA Department of Aging Local Resources page (https://www.google.com/search?q=https://www.pa.gov/agencies/aging/local-resources/area-agencies-on-aging)to look up the contact information for your specific county.",
          "hours": "Contact your county AAA for specific hours"
        }
      ],
      "applicationNotes": [
        "Family members cannot be hired or paid to provide care to relatives through this program",
        "Above 380% Federal Poverty Level, you can still access non-financial services like care management and education",
        "Each county's Area Agency on Aging has different procedures and wait times",
        "You must pay for services upfront and seek reimbursement, no direct payment to providers"
      ],
      "relatedPrograms": [
        "PA OPTIONS Program",
        "PACE Program",
        "Pennsylvania SNAP Benefits"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can I get reimbursed if my loved one's income is too high?",
          "answer": "If your loved one's household income is above 380% of the Federal Poverty Level ($58,320 for a single person in 2026), you won't get financial reimbursement. However, you can still access non-financial services like care management, caregiver education, and training at no cost."
        },
        {
          "question": "What expenses can I actually get reimbursed for?",
          "answer": "The program reimburses for respite care, supplemental services, consumable supplies, and other care-related expenses approved by your care manager. The specific services must be authorized during your in-home assessment. You cannot be reimbursed for hiring family members to provide care."
        },
        {
          "question": "How long does it take to get my money back after submitting receipts?",
          "answer": "Reimbursement timelines vary by county since each Area Agency on Aging processes payments differently. Ask your local AAA about their typical processing time when you apply."
        },
        {
          "question": "Can I apply if I'm caring for my spouse who has Alzheimer's?",
          "answer": "Yes, if your spouse has Alzheimer's or a related disorder at any age, you qualify as long as you both live in Pennsylvania and you're the primary caregiver. There's no relation or co-residence requirement for Alzheimer's care."
        },
        {
          "question": "What if my loved one lives in one Pennsylvania county but I live in another?",
          "answer": "Both you and your care receiver must live in Pennsylvania, but you don't need to live in the same county. Contact the Area Agency on Aging in your loved one's county of residence since that's where they'll receive services."
        },
        {
          "question": "Can I use this program and Medicaid waiver services at the same time?",
          "answer": "Generally, individuals enrolled in Medicaid Long-Term Services and Supports (such as Community HealthChoices or the LIFE program) are not eligible for the Caregiver Support Program, as those programs already provide comprehensive caregiving support. If your loved one is considering enrolling in a Medicaid waiver, discuss how this may impact your eligibility for the Caregiver Support Program with your local Area Agency on Aging during your initial assessment."
        },
        {
          "question": "What happens if my loved one's income changes after I'm enrolled?",
          "answer": "Your reimbursement percentage is based on your loved one's current household income, so changes may affect your reimbursement rate. Report income changes to your care manager who will adjust your reimbursement percentage accordingly."
        },
        {
          "question": "Do I need to live with my loved one to qualify for this program?",
          "answer": "For caring for someone 60+ with functional deficits or anyone with Alzheimer's, you don't need to live together or be related. Co-residence is only required for caregivers 55+ caring for grandchildren under 18 or disabled adults 18-59."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "step-journey",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "editorial"
      },
      "icon": "HandHeart",
      "phone": "(717) 783-1550",
      "sourceUrl": "https://www.pa.gov/agencies/aging/aging-programs-and-services/caregiver-support-program",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "oplap-legal-assistance",
      "name": "Older Pennsylvanians Legal Assistance Program (OPLAP)",
      "shortName": "OPLAP Legal Aid",
      "tagline": "Free legal help for Pennsylvania seniors facing housing problems, benefit denials, or healthcare disputes.",
      "programType": "resource",
      "complexity": "simple",
      "geographicScope": {
        "type": "state",
        "stateVariation": false,
        "localEntities": [
          {
            "name": "Pennsylvania SeniorLAW Helpline (statewide)",
            "type": "service-area"
          },
          {
            "name": "SeniorLAW Center (Philadelphia-based admin)",
            "type": "service-area"
          },
          {
            "name": "PA Legal Aid Network local programs",
            "type": "service-area"
          },
          {
            "name": "County Area Agencies on Aging",
            "type": "service-area"
          },
          {
            "name": "PALawHelp.org for county locator",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one is 60+ and struggling with legal issues like eviction notices, denied Medicare claims, or Social Security problems, they may qualify for free legal help through Pennsylvania's senior legal aid program. OPLAP provides attorneys who specialize in elder law issues, from fighting benefit denials to defending against guardianship proceedings.\n\nEligibility is generally based on 125% of the federal poverty level (about $1,900/month for a single person in 2026), with priority given to seniors with the greatest economic and social needs. The program covers legal matters related to abuse, age discrimination, healthcare, housing, long-term care, Medicaid, Medicare, nutrition, Social Security/SSI, and utilities. Your loved one pays only court filing fees, attorney services are free.\n\nHigh demand means many qualified seniors can't be served immediately. At least 80% of legal needs among low-income older adults go unmet nationally due to limited resources.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": true,
      "structuredEligibility": {
        "summary": [
          "Age 60+",
          "Pennsylvania resident",
          "Income around 125% of poverty level",
          "Legal issue in covered areas"
        ],
        "ageRequirement": "60+",
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Pennsylvania resident",
          "Legal matter must relate to abuse, age discrimination, guardianship defense, healthcare, housing, long-term care, Medicaid, Medicare, nutrition, Social Security/SSI, or utilities",
          "Priority given to those with greatest economic and social needs"
        ],
        "povertyLevelReference": "125% FPL"
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call the Pennsylvania SeniorLAW Helpline at 1-877-727-7529 for immediate screening and referral to local legal aid.",
        "steps": [
          {
            "step": 1,
            "title": "Call the helpline",
            "description": "Call Pennsylvania SeniorLAW Helpline at 1-877-PA SR LAW (1-877-727-7529) to describe your loved one's legal issue and get screened for eligibility."
          },
          {
            "step": 2,
            "title": "Complete intake screening",
            "description": "Answer questions about your loved one's age, income, residence, and the specific legal problem. The helpline will determine if the case fits program priorities."
          },
          {
            "step": 3,
            "title": "Get referred to local provider",
            "description": "If eligible, you'll be connected to your county's legal aid program or Area Agency on Aging for direct legal assistance or representation."
          }
        ],
        "processingTime": null,
        "waitlist": "High demand may result in turnaways despite qualification due to limited resources",
        "tip": "Call early in the day, high demand means phone lines can get busy, and some qualified seniors may be turned away due to capacity limits.",
        "urls": [
          {
            "label": "PALawHelp.org",
            "url": "https://www.palawhelp.org"
          },
          {
            "label": "SeniorLAW Center",
            "url": "https://www.seniorlawcenter.org"
          }
        ]
      },
      "documentsNeeded": [
        "Valid government-issued photo ID or birth certificate (proof of age)",
        "Proof of Pennsylvania residency (utility bill, lease, or state-issued document)",
        "Social Security award letter or other income documentation",
        "Documents related to the legal issue (court notices, eviction papers, benefit denial letters, medical bills)",
        "Medicare card and health insurance information if issue is healthcare-related",
        "Lease agreement or property documents if issue is housing-related"
      ],
      "contacts": [
        {
          "label": "Pennsylvania SeniorLAW Helpline",
          "phone": "(877) 727-7529",
          "description": "Statewide legal aid screening and referral for seniors",
          "hours": "Hours: Monday through Thursday, 10:00 a.m. to 12:00 p.m."
        },
        {
          "label": "Pennsylvania 2-1-1",
          "phone": "2-1-1",
          "description": "General social services helpline that can also connect to legal aid",
          "hours": "24 hours, 7 days a week"
        }
      ],
      "applicationNotes": [
        "The program cannot help with divorce, property settlements, or family disputes, only issues specifically related to elder law and basic needs",
        "Even if your loved one qualifies, they may be turned away due to high demand and limited attorney capacity in their county"
      ],
      "relatedPrograms": [
        "Area Agency on Aging services",
        "Pennsylvania APPRISE (Medicare counseling)",
        "Adult Protective Services"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "What if my loved one's legal issue isn't on the covered list?",
          "answer": "If your loved one’s specific legal issue isn't listed, don't let that stop you from calling. The program is designed to protect the rights, health, and independence of older Pennsylvanians, focusing on areas like housing, healthcare, and public benefits. While OPLAP is not generally designed for matters like contested divorce or complex property settlements, local legal providers may have other resources or be able to offer guidance on how to find the right support for your situation. It is always best to contact your local Area Agency on Aging to discuss your specific needs."
        },
        {
          "question": "Can I apply on behalf of my loved one who has dementia?",
          "answer": "Yes, family members can call the helpline to discuss legal issues affecting their aging loved ones. However, the attorney will need to communicate directly with your loved one when possible, or work through proper legal channels if guardianship or power of attorney is involved."
        },
        {
          "question": "How long does it take to get connected with an attorney?",
          "answer": "Processing time varies by county and case urgency. The helpline can provide immediate screening, but connection to a local attorney depends on capacity in your area. Some counties may have immediate availability while others have waiting periods due to high demand."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "phone-cta",
        "hasLocationFinder": true,
        "hasDocumentChecklist": true,
        "visualTone": "warm"
      },
      "icon": "Scales",
      "phone": "(877) 727-7529",
      "sourceUrl": "https://www.pa.gov/services/aging/apply-for-the-older-pennsylvanians-legal-assistance-program",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    },
    {
      "id": "ltc-ombudsman",
      "name": "Long-Term Care Ombudsman Program",
      "shortName": "LTC Ombudsman",
      "tagline": "Free advocate to resolve nursing home or assisted living complaints and protect your loved one's rights.",
      "programType": "resource",
      "complexity": "simple",
      "geographicScope": {
        "type": "federal",
        "stateVariation": true,
        "localEntities": [
          {
            "name": "Local Area Agencies on Aging (AAA); State office: Pennsylvania Department of Aging, 555 Walnut Street, 5th Floor, Harrisburg, PA 17101",
            "type": "service-area"
          }
        ]
      },
      "intro": "If your loved one lives in a nursing home, assisted living facility, or receives long-term care at home in Pennsylvania, they have a free advocate available when problems arise. The Long-Term Care Ombudsman Program investigates complaints, mediates disputes with facilities, and educates families on resident rights, at no cost regardless of income.\n\nOmbudsmen handle issues like discharge threats, medication errors, lost personal property, poor food quality, inadequate staffing, billing problems, and dignity violations. Because they have legal authority to enter facilities unannounced and access records, they can resolve problems that families struggle with alone. Services extend to family members advocating for residents, but require the resident's permission before intervening with facility staff.",
      "savingsRange": "",
      "savingsSource": "Free service",
      "savingsVerified": false,
      "structuredEligibility": {
        "summary": [
          "Resident of PA long-term care facility",
          "Or receiving LTC services at home",
          "Family members can request help",
          "No income or asset limits",
          "Completely free"
        ],
        "ageRequirement": null,
        "incomeTable": null,
        "assetLimits": null,
        "functionalRequirement": null,
        "otherRequirements": [
          "Must be related to quality of care, resident rights, or facility policies",
          "Resident permission required before ombudsman speaks with facility staff"
        ],
        "povertyLevelReference": null
      },
      "applicationGuide": {
        "method": "phone",
        "summary": "Call your county's Area Agency on Aging ombudsman, no application needed, just describe the problem.",
        "steps": [
          {
            "step": 1,
            "title": "Contact your county's ombudsman",
            "description": "Call your local Area Agency on Aging ombudsman program directly. Each county has its own number, for example, Franklin County (717-299-7979), Montgomery County (610-278-1320), or the statewide Elder Abuse Hotline (1-800-490-8505)."
          },
          {
            "step": 2,
            "title": "Describe the complaint",
            "description": "Explain the specific issue, discharge threat, medication problem, billing dispute, quality of care concern, or rights violation. Provide the facility name and resident's name."
          },
          {
            "step": 3,
            "title": "Ombudsman investigates",
            "description": "The ombudsman will visit the facility, review records, interview staff and residents, and work to resolve the complaint through mediation and advocacy."
          }
        ],
        "processingTime": "Ombudsmen respond promptly to complaints, but no specific timeline provided",
        "waitlist": null,
        "tip": "Have the facility name, resident's name, and specific details of the problem ready when you call.",
        "urls": [
          {
            "label": "PA Department of Aging Advocacy Programs",
            "url": "https://www.pa.gov/agencies/aging/aging-programs-and-services/advocacy-education-protection"
          }
        ]
      },
      "documentsNeeded": null,
      "contacts": [
        {
          "label": "Elder Abuse Hotline",
          "phone": "1-800-490-8505",
          "description": "Statewide hotline for elder abuse and ombudsman referrals",
          "hours": "24 hours, 7 days a week"
        },
        {
          "label": "PA State Ombudsman Office",
          "phone": "717-783-8975",
          "description": "555 Walnut Street, 5th Floor, Harrisburg, PA 17101 - for statewide coordination",
          "hours": "Business hours"
        }
      ],
      "applicationNotes": null,
      "relatedPrograms": [
        "Adult Protective Services",
        "Area Agency on Aging Services",
        "PA Department of Health Facility Licensing"
      ],
      "contentSections": [],
      "faqs": [
        {
          "question": "Can I file a complaint if my loved one has dementia and can't give permission?",
          "answer": "Yes. If your loved one has dementia or is unable to express their wishes, you can contact the Ombudsman on their behalf. The Ombudsman will work to protect your loved one’s rights and quality of life by making decisions based on what your loved one would want if they could express it (their 'substituted judgment') or what is in their best interest. They will still maintain confidentiality and advocate for your loved one’s dignity and safety, but they will look to you as a representative or family member to help them understand your loved one’s needs and values."
        },
        {
          "question": "What if the facility retaliates against my loved one after I file a complaint?",
          "answer": "Retaliation is illegal and a serious violation. Report any retaliation immediately to the ombudsman, who has legal authority to investigate and take action. Federal and state laws specifically protect residents and families who file complaints or speak with ombudsmen."
        },
        {
          "question": "Will filing a complaint affect my loved one's care or get them kicked out?",
          "answer": "No, facilities cannot discharge or transfer residents in retaliation for complaints. If they attempt to do so, that becomes an additional violation the ombudsman will address. Most complaints are resolved through mediation without adversarial proceedings."
        }
      ],
      "layoutIntent": {
        "aboutHighlight": "coverage",
        "eligibilityDisplay": "simple-list",
        "applyDisplay": "phone-cta",
        "hasLocationFinder": true,
        "hasDocumentChecklist": false,
        "visualTone": "minimal"
      },
      "icon": "Scales",
      "phone": "1-800-490-8505",
      "sourceUrl": "https://www.pa.gov/agencies/aging/aging-programs-and-services/advocacy-education-protection",
      "contentStatus": "approved",
      "draftedAt": "2026-04-13",
      "reviewedBy": "Cecille Chavez",
      "reviewedAt": "2026-06-17"
    }
  ],
  "stateOverview": {
    "intro": "Pennsylvania offers 9 programs that can save your aging loved one hundreds of dollars monthly and connect you with free support services. Six are qualification-based benefits, like Community HealthChoices covering up to 32 home care services, PACE providing low-cost prescriptions, or SNAP adding up to $300/month for groceries. Three are free resources available to all Pennsylvania seniors, including SHIP counseling to navigate Medicare and legal assistance through OPLAP. Most income-based programs use similar thresholds, so if your loved one qualifies for one, they may qualify for several. Start by checking the programs below that address your most urgent need, financial help, daily care support, or free guidance.",
    "startHere": [
      {
        "name": "Community HealthChoices (CHC)",
        "programId": "community-healthchoices-chc",
        "why": "Covers the most expensive need, daily personal care and health services at home, if your loved one is dual eligible or needs daily assistance."
      },
      {
        "name": "SNAP (Supplemental Nutrition Assistance Program)",
        "programId": "snap",
        "why": "Quick financial relief with up to $300/month for groceries, and eligibility often indicates qualification for other programs."
      },
      {
        "name": "SHIP (State Health Insurance Assistance Program)",
        "programId": "ship",
        "why": "Free for everyone and can immediately identify Medicare cost savings your loved one may be missing."
      }
    ],
    "byNeed": [
      {
        "need": "Help paying for daily care at home",
        "programs": [
          "LIFE (Living Independence for the Elderly)",
          "Community HealthChoices (CHC)",
          "Caregiver Support Program"
        ],
        "description": "Financial assistance for personal care, home health services, and respite care support."
      },
      {
        "need": "Lower medical and prescription costs",
        "programs": [
          "PACE (Pharmaceutical Assistance Contract for the Elderly) in Pennsylvania",
          "Healthy Horizons (QMB, SLMB, QI)"
        ],
        "description": "Reduced prescription costs and Medicare premium coverage for seniors with limited income."
      },
      {
        "need": "Food assistance",
        "programs": [
          "SNAP (Supplemental Nutrition Assistance Program)",
          "Home-Delivered Meals (Meals on Wheels)"
        ],
        "description": "Monthly grocery benefits or free delivered meals if your loved one can't shop or cook safely."
      },
      {
        "need": "Free advice and advocacy",
        "programs": [
          "SHIP (State Health Insurance Assistance Program)",
          "Older Pennsylvanians Legal Assistance Program (OPLAP)",
          "Long-Term Care Ombudsman Program"
        ],
        "description": "One-on-one counseling, legal help, and advocacy services available to all Pennsylvania seniors."
      }
    ],
    "quickFacts": [
      "Pennsylvania's Community HealthChoices program serves as the main pathway for Medicaid long-term care services, covering up to 32 different home and community-based services.",
      "PACE prescription program is specific to Pennsylvania seniors 65+ and provides significant drug cost reductions beyond standard Medicare coverage.",
      "Three free resource programs (SHIP, OPLAP, Long-Term Care Ombudsman) have no income limits and are available to any Pennsylvania senior or their family."
    ],
    "resourcesVsBenefits": "Six programs require qualification based on income, age, or care needs, these provide direct financial assistance like Community HealthChoices covering home care services or SNAP providing grocery money. Three programs are free resources available to any Pennsylvania senior regardless of income, SHIP for Medicare guidance, OPLAP for legal help, and the Ombudsman for nursing home advocacy. Even if your loved one's income is too high for financial benefits, these free resources can still save money through better Medicare choices and problem resolution."
  }
};
